### ISSUE TITLE
show number of commits next to each user in revision tab

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#100]
From the modelers feedback in #71:

`in the "authors" widget, it would be good to show the number of concepts (not edits) as well as the number of conflicting concepts next to each author's name.)`

This is a little tricky to obtain, however showing the commit count for each user, which roughly corresponds to the number of concepts edited, merged, split or retired, is.

**Comment by bdionne** [comment]
ready in [nci-0.107](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.107)

**Comment by rmehri** [comment]
The fix for number of commits next to each user in revision history tab has been retested and verified using tag-115.  Please see attached screen shot for more detail.

Thanks,
Reza

![revision history](https://cloud.githubusercontent.com/assets/8367102/21619545/22196cbc-d1be-11e6-8361-cac7b6aeb486.png)
