### ISSUE TITLE
Tag-112-Warning Message-Missing Properties When Openning a Projectby 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#137]
Steps to reproduce:
1.Launch server and client
2.Log into local host http://localhost:8080 
3.Use "reza" (WorkFlow Modeler) 
4.Select ProjectByName  and open the project
5. You'll see the following warning"Missing properties"
6. Click Ok and then you can continue with navigation. 
Please attached snapshot for more details.
Thanks,
 Reza

![error opening projectbyname](https://cloud.githubusercontent.com/assets/8367102/21323880/66fa920c-c5ed-11e6-99ff-2e0e3dec4a1c.jpg)

**Comment by bdionne** [comment]
@rmehri - This works as intended. I added a complex property to the default config file for by name, called `foo`. It has no qualifiers. You see the warning because it does not exist in your ontology.

I put it there to test #32 - better display of complex properties that have not qualifiers yet.

You can do one of two things to make the warning go away, either create an annotation property in your ontology named `foo`, or delete the reference from the config file.

**Comment by rmehri** [comment]
As per development's comment and also wontfix, this ticket can be closed.
