### ISSUE TITLE
ability to restrict connections to the server without shutting it down

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#150]
We'd need it so that baseline reconciliation & conflict resolution can be done by admin roles without new edits affecting the process coming in from modeler roles.  

Can slip for a future release soon after v1.  Until then, modelers would have to, by guideline, cease editing while the reconciliation/conflict resolution process is completed.

**Comment by bdionne** [comment]
This shouldn't be too hard, all the pieces are there. Basically we need to keep the web server running so that the `workflow manager` can accept/reject/download/etc.. but the `workflow modelers` cannot do anything. 

One question is how to surface it, .ie. how to switch into this restricted mode. We can either add a button or menu item in the revision diff panel, only usable by managers, or have an endpoint on the admin port (8081) and force the managers to login on that port first and do it through the admin panel.
This is an extra step for the managers, but might be preferable as this is something we don't want them to `accidentally` execute.

**Comment by bdionne** [comment]
The [latest](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.115) build has a pass at implementing this.

When a workflow manager is logged in a new menu item in the server menu is enabled:

<img width="1020" alt="screen shot 2017-01-03 at 7 52 35 am" src="https://cloud.githubusercontent.com/assets/31741/21608908/73d8dd70-d18d-11e6-91c1-dfa3c447726e.png">

When selected this item pauses the server:

<img width="1017" alt="screen shot 2017-01-03 at 7 52 57 am" src="https://cloud.githubusercontent.com/assets/31741/21608916/878bcd3c-d18d-11e6-9d7e-47dea1d34e3d.png">

What a workflow modeler sees when attempting to commit is:

<img width="1019" alt="screen shot 2017-01-03 at 7 53 34 am" src="https://cloud.githubusercontent.com/assets/31741/21608948/ab6db788-d18d-11e6-8f0e-23c135548d6f.png">

With a message that says to try later. Once the server has been resumed the save will work. Any commits that the manager makes in the interim will work. This enables work in the revision tab, accepting and rejecting and extracting concept history, to proceed without interference from any new edits.

**Comment by rmehri** [comment]
This fix has been retested and verified using tag -115. The pause server tab gets enabled by using Workflow Manager and Workflow Modeler logins .  Please see attached snapshots for more details. 
Thanks,
Reza
![pause_server -workflow_modeler](https://cloud.githubusercontent.com/assets/8367102/21655892/d04428ce-d289-11e6-9701-23970dc75b6f.png)
![pause_server -workflow_manager_-1](https://cloud.githubusercontent.com/assets/8367102/21655905/dc009dd2-d289-11e6-8e27-38cb20540954.png)
![pause_server -workflow_manager-2](https://cloud.githubusercontent.com/assets/8367102/21655920/e55c467e-d289-11e6-8bca-fc0a48aec584.png)
