### ISSUE TITLE
notification when opening a project

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#164]
The user can't tell currently when a vocabulary snapshot has finished loading into the GUI, except by looking at the console, but you still have to infer it based on the activity in the console.  Would be good to have some kind of pop-up notification, progress bar, or opening up the hierarchy in the tree widget.

**Comment by bdionne** [comment]
Fixed in 2.2.0-beta2

**Comment by singhik** [comment]
QA has verified the presence of a progress bar post logging and Selecting a Project, The progress bar goes via following stages : 

“Opening Project On Server ->Checking Snapshot Checksum->Building Versioned Ontology->Updating Menus and Components->Updating Search Indices->Operations Complete”

![image](https://user-images.githubusercontent.com/36314371/36736974-ea660ff2-1ba7-11e8-94d0-cc68d42b13bd.png)


![image](https://user-images.githubusercontent.com/36314371/36736982-efdb2db4-1ba7-11e8-90cc-e279a55ece8a.png)

**Comment by bdionne** [comment]
@singhik - yea there was no real spec for these stages, what you observe seems correct. If you look at the [code](https://github.com/bdionne/protege-client/commit/5a886b716573de4da6c7441e45c5e1ce1b51f874) what Yinghua did was just to put in some progress indicators at points that seemed reasonable in terms of what's going on internally. 

It might help when there are problems, as the users can tell us where it failed, but otherwise the intent is just to create the impression work is progressing
