### ISSUE TITLE
eliminate primitive and defined attributes from batch edit files

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#174]
Applies to [parent and role batch edits](https://github.com/NCIEVS/nci-protege5/wiki/batch-edit-formats).  To go with this, the defined/primitive state of the concept might still need to be modified during a batch:
- if a role or a parent is deleted from a defined class, convert to primitive
- don't delete the last parent of a concept (independent of P or D)

**Comment by bdionne** [comment]
The type field has now been eliminated from batch edits of parents and roles.

Conversion if defined to primitive is still a `TODO`

**Comment by rmehri** [comment]
Hi, 
I have retested this issue for Parents and Role batch Edit testing, I keep getting a failure to validate the fix for the issue below. As per double checking,  I addressed a few questions about these two functionalities.  Please see attached snapshots for more detail and let me know your feedback,  

![parents_roles_batch files](https://cloud.githubusercontent.com/assets/8367102/22760770/e55f4a6a-ee25-11e6-89b2-e539c3e38fb2.png)

![test_partentbycode](https://cloud.githubusercontent.com/assets/8367102/22760843/48d55832-ee26-11e6-9741-5835173c7280.png)

Thanks,
Reza

**Comment by bdionne** [comment]
Not sure I follow, what specifically is failing? Those ids in the tables on the WIKI refer to class ids. Every class has a unique code. 

The second screenshot looks like you are running a batch load. Those tables refer to batch edits.

We can review how this works tomorrow if it's not clear.

**Comment by bdionne** [comment]
Still not clear to me what is "failing to validate?"

**Comment by rmehri** [comment]
Hi, 
This fix has been retested and verified in tag-123, edittab-0.4.6. Please attached screen shot and batch edit files.

![bathedit_add_role1](https://cloud.githubusercontent.com/assets/8367102/23274157/ab25609a-f9cf-11e6-8445-10bc6991f965.png)
[testParents_BatchLoad-1.txt](https://github.com/NCIEVS/nci-protege5/files/797423/testParents_BatchLoad-1.txt)
[testParents_BatchLoad-1-out.txt](https://github.com/NCIEVS/nci-protege5/files/797424/testParents_BatchLoad-1-out.txt)
[Batch_Edit_Add Role1.txt](https://github.com/NCIEVS/nci-protege5/files/797425/Batch_Edit_Add.Role1.txt)
[Batch_Edit_Add Role1-Out.txt](https://github.com/NCIEVS/nci-protege5/files/797426/Batch_Edit_Add.Role1-Out.txt)
[Batch_Edit_Modify Role1.txt](https://github.com/NCIEVS/nci-protege5/files/797427/Batch_Edit_Modify.Role1.txt)
[Batch_Edit_Modify Role1-out.txt](https://github.com/NCIEVS/nci-protege5/files/797428/Batch_Edit_Modify.Role1-out.txt)

Thanks,
Reza
