### ISSUE TITLE
Issues with Revision Diff

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#175]
- commits are too noisy, multiple commits of the same class, when only the last one is useful

- changes aren't presented with a class or concept focus

- concept history fails with null pointer, see email (#228)

- create new project hangs on memory constrained client (#178)

**Comment by NCIEVS** [comment]
Some other observations, not necessarily orthogonal to the above
- need easier way to find conflicts
- multisort, e.g. by conflict & concept, otherwise the changes by concept are all over the place
- accept -> refreshes & reinitializes the changes view
- when accept/reject after review, don't show that change again (if prior to a squash)

**Comment by NCIEVS** [comment]
The "comment" column in the Changes widget doesn't quite match edit actions.  E.g. a "create" event is not logged, but all the activities related to creating a concept appear as "edit", add a preferred_name, add an rdfs:label, add a superclass, add a semantic_type, add a code.  We should review the actions and eventually modify the messages that appear under "comment."

**Comment by NCIEVS** [comment]
Question, might need development:  

On reject, does the rejected evs_history record get purged?  Or do we wind up with two "modify" actions that are not reflected in the vocabulary content?

**Comment by bdionne** [comment]
review with Liz

**Comment by bdionne** [comment]
see #504

**Comment by NCIEVS** [comment]
Just to add that the only item that still required follow-up was the second bullet, now in the new ticket mentioned above.
