### ISSUE TITLE
Tag-118-Batch Edit-Editing Complex Property Results Exception Error 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#187]
Steps to reproduce:
Modeler Role:  http://localhost:8080
Edittab-0.3.5

1) Log into in the local server
2) Select NCI Edit Tab
3) Select Batch Load/Edit and upload attached batch file 
4) Select Batch Type= Edit_Complex_Props
5) You'll see the follow error.

Please see attached zip file for more detail.

Feb 7, 2017

processing: C1000041	modify	DEFINITION	The type of Gene for Testing.  	Definition_Reviewer_Name	This is a test user.	Defintion_Review_Date	2017-02-06	def-source	NCI	DEFINITION	The type of Cell for Testing. 	Definition_Reviewer_Name	Modeler is a test user.	Defintion_Review_Date	2017-03-06	def-source	FDA
record 1: Exception caughtjava.lang.ArrayIndexOutOfBoundsException: 19 >= 18
Total run time was: 2 ms
Total successful completion: 0 out of: 1

[Edit_Properties To_ ClassByName-3_out.zip](https://github.com/NCIEVS/nci-protege5/files/758537/Edit_Properties.To_.ClassByName-3_out.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - this has a similar problem to the other batch edit tickets, you have spurious tabs in the input file

I found out notepad does have a mode that allows you to see the tabs. This should help you produce the correct input file. If you fix the file you'll see an error due to the qualifiers being immutable. If you remove those it works fine
