### ISSUE TITLE
Issues from UAT training

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#200]
* navigation tree sometimes loses focus, and adding a prop happens on another class (#245, #260)

 * check ordering of search results (#246)

 * editing the source in split/clone ops

 * issues with control when using dual-edits. User could select dual edit when they had a merge active

 * search is still lacking, issues with stop words and ability to find phrases in property values (#251, the ANDed search w/o stopwords needs to be gauged against actual searches, as well as "contains" in a full string search, #163)

 * in export, selecting properties is awkward, no memory on re-edits, missing properties like DEFINITION, exporting cached queries by mistake (this has been fixed, #151)

 * LOAD should not be default for batch edit combobox, or at least capture and remember the user's preference

**Comment by hahndane** [comment]
Hi Bob
On that last one, I am not sure remembering the user's preference is any better than having LOAD as default. When we only had two options (Load and Edit), Load is used less frequently so it made sense to have Edit as the default. Now that we have LOAD, EDIT_COMPLEX_PROPS, EDIT_SIMPLE_PROPS, EDIT_PARENT and EDIT_ROLES, I am not sure which to default to because EDIT_COMPLEX_PROPS and EDIT_SIMPLE_PROPS will be the ones used most frequently and I don't know which the editors would prefer.

Liz

**Comment by bdionne** [comment]
well remembering the preference will certainly help when they run it several times in one session, so perhaps remembering the preference *and* making either `EDIT_SIMPLE_PROPS` or `EDIT_COMPLEX_PROPS` the default would help.

**Comment by bdionne** [comment]
If `LOAD` is not the default, then what should be?

**Comment by hahndane** [comment]
I think we need to ask Teri, Erin and Jordan what they want the default to be. They do the most batching.

**Comment by bdionne** [comment]
These items are now either fixed or accounted for in other tickets
