### ISSUE TITLE
enhanced support for dual-editing

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#208]
Add copy/paste buttons or right click menu items to Dual-Editing panel.  Currently copy-paste can only be done through the keyboard, ^c/^V

**Comment by bdionne** [comment]
Itendra: Dual Edit panel here is 'NCI Edit Tab->ComplesEdit->Dual Edits' ? and will the copy & paste options be present on the panel as radio buttons or as options post right click on a class/concept ?

The copy/paste operations are the same. The major change here is that new icons will appear on the complex properties, and when they are edited the dialogs that are use when editing in the main edit panel will be used instead of the protege ones.

<img width="1021" alt="screen shot 2018-02-16 at 10 31 58 am" src="https://user-images.githubusercontent.com/31741/36315045-b23f0562-1304-11e8-985d-e6e41f3a5bd8.png">

<img width="1017" alt="screen shot 2018-02-16 at 10 32 12 am" src="https://user-images.githubusercontent.com/31741/36315064-bb239170-1304-11e8-9a39-6ad097408c41.png">

**Comment by singhik** [comment]
QA has validated the presence of  three buttons(Add,Edit and Delete)  on 'Dual Edit' Panel  for Complex properties and have verified addition ,edition and deletion of Complex properties via those buttons for both Source and Target Class ...
Attached are the screen prints for reference ..
[Issue 208.docx](https://github.com/NCIEVS/nci-protege5/files/1741674/Issue.208.docx)

**Comment by hahndane** [comment]
This is a nice enhancement allowing the complex properties to be edited in the ComplexEdit tab like they are in the Edit tab but there appears to still not be a way to copy/paste annotations between concepts without using the keyboard.

This is an enhancement that we should demo to the editors when this release goes to prod.

**Comment by bdionne** [comment]
copy/paste continues to work the way it always did, even for complex properties. Not sure what you mean by without keyboard, are you referring to right click menus?

**Comment by hahndane** [comment]
Yes, the current v2.2.0 on stage does not have copy/paste in the right click menus when you select a property. (It looked like this ticket says they would have this.)

**Comment by bdionne** [comment]
I see, we can open a new ticket for this separately if this is something modelers will use regularly

**Comment by hahndane** [comment]
I don't know how much other modelers are using the current copy/paste so I don't know this feature is worth a ticket.

Actually, can we open a new ticket to allow for selection of multiple properties to copy and paste in the Edit and ComplexEdit tabs. Right now you can select multiple properties by holding the ctrl key but the copy/paste only works when you have one property selected. 
Usecase: for CDISC, FDA and other projects you may have multiple shared properties (mostly Concept_in_Subset and Contributing_Source) when adding new concept. For example, all concepts in the CDISC SDTM subset have Contributing_Source=CDISC, Concept_in_Subset=Clinical Data Interchange Standards Consortium Terminology, and Concept_in_Subset=CDISC SDTM Terminology, so it would be nice to copy these all from an existing concept to place in either a new concept or an existing concept that is new to CDISC SDTM. (This is a low priority because most of this editing is currently done in batch but it would be useful for new singleton items that are identified after the batches are done and the editor is doing QA on the set and for smaller subsets where concepts are created manually.)
