### ISSUE TITLE
From UAT [NS 2/27] - default search property

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#217]
Presumably, [user] has set his default search to property = FULL_SYN but when he searches the hierarchy to add a parent or role filler value the property = label. (I need to go back and confirm he changed this.)

**Comment by bdionne** [comment]
Itendra: Does this requirement refer to the 'Search' criteria from 'NCI Edit->Search->Lucene Query Dialog' ,Property Drop down list ,to have 'FULL_SYN' as default value instead of 'label' ?

Yes the user can set the default property in the search settings, but then that property should show up in the LQT but also anywhere the search is used, .eg. in the object restriction editor (see screenshots below)

<img width="1012" alt="screen shot 2018-02-16 at 10 26 13 am" src="https://user-images.githubusercontent.com/31741/36314876-2629d7d2-1304-11e8-8db9-13f393e3aab5.png">

<img width="1227" alt="screen shot 2018-02-16 at 10 26 56 am" src="https://user-images.githubusercontent.com/31741/36314887-2c2e241c-1304-11e8-8af1-f86022649490.png">

**Comment by singhik** [comment]
QA verified for the Default Search criteria  set to be visible in other Search navigations . Used boundary value navigations for 
‘Lucene Search Tab’
‘NCI Edit Tab’->’Search’ 
‘NCI Edit Tab’->’Edit’->’Description’->’SubClass of’->’Object restriction creator’->'Search'
 ‘NCI Edit Tab’->’Edit’->’Description’->’SubClass of’->’Class hierarchy’->'Search'
‘Annotation properties’->’Annotations’->’Entity IRI’->’Search’
‘Annotation properties’->’Annotations’->’Domains’->’Select Class’->’Search’

Attached is the document with screen prints for reference .
[Issue 217.docx](https://github.com/NCIEVS/nci-protege5/files/1741038/Issue.217.docx)
