### ISSUE TITLE
failure to commit from Revision History when the server is paused

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#228]
It might be a matter of permissions.  The managers have both Administrator and Workflow Manager roles.

**Comment by bdionne** [comment]
appears to be fixed in current build

**Comment by rmehri** [comment]
Hi, 
I have retested this issue for accept a change while my local server was at pause state. I successfully committed the change. 
Used latest tag: nci-1.003, nci-edit-tab-0.5.6, lucene-search-tab-1.0.2 .
Login Role: Workflow-manager
Please see attached screenshot for more detail.

![revision history](https://cloud.githubusercontent.com/assets/8367102/25204032/b94a3f80-2529-11e7-88ef-4165bc77522c.png)

Thanks,
Reza

**Comment by rmehri** [comment]
Hi,
One more note to add to this issue that when my local server is at pause state, commit rejection fails. In this case, this ticket remains closed since the related ticket is still outstanding. We will retest when this issue is resolved https://github.com/NCIEVS/nci-protege5/issues/191.
Thanks,
Reza
