### ISSUE TITLE
Tag-0125-NCI-Edit Tab-Duplicated Class Allowed

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#240]
Used:
Servers: http://localhost:8080 & https://nciws-d699-v.nci.nih.gov:9090
Logins: Modeler & Manager
Tag-125 & NCI Edit-0.5.0
Steps to reproduce:
1.	Launch protégé server and client
2.	Log into the local server (8080)
3.	Select NCI Edit Tab
4.	Select a class parent
5.	Under top left navigator, click + sign to add Sub Class
6.	Enter a duplicated name same as selected class parent ( from step# 4) in “Create a New OWLClass” popup menu.
7.	This warning message displays “Entity already exists: i.e…”
8.	Click Ok and you’ll see it allows a user to save the duplicated class although received the warning message! 
9.	Repeat steps1 through 8 using https://nciws-d699-v.nci.nih.gov:9090, and you’ll see no warning message displays and also the duplicated class can be saved as well. 

Please see attached screen shots for more detail. 

![duplicate class](https://cloud.githubusercontent.com/assets/8367102/24214238/49804dc2-0f0b-11e7-8ab4-d159d43b3d9a.png)
![duplicate class-1](https://cloud.githubusercontent.com/assets/8367102/24214250/51007cb6-0f0b-11e7-9479-d6e18071818f.png)
![duplicate class-2](https://cloud.githubusercontent.com/assets/8367102/24214253/52c42f8e-0f0b-11e7-865e-75f4cf8251d3.png)

Thanks,
Reza

**Comment by bdionne** [comment]
I"m not sure this is a bug, maybe enhancement.

You are seeing this because the `preferred_name` you enter is the same as the `IRI` of another class. If you look at the new class you'll see it has a different code, it's not a duplicate it just has the same `preferred_name`. All this dialog does is check for duplicate IRIs and warns the user.

That said, we do prevent this in batch load by doing a search over `preferred_names` and kicking out records that are duplicates. We can do a similar thing here.

So the question is (for @NCIEVS ),  should we prevent dups in the editor?

**Comment by NCIEVS** [comment]
Yes, we allow duplicate preferred_names for classes.  It doesn't mean that the classes are duplicates, only that they have the same preferred term.  This is very common.  The users need a warning, but the edit has to be allowed to complete.

**Comment by rmehri** [comment]
Hi,
Thanks for clarification and feedback!
Reza
