### ISSUE TITLE
Strange behavior when editing parents

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#245]
From Liz:

Also, I guess this will be a future release feature request, when you change a parent (either through editing or adding new/removing old) to be in a branch that is not open in the hierarchy pane, even before you save, the GUI behaves strangely. The Edit panel data clears and the hierarchy compresses down to owl:thing. The Save button still becomes available and you can save the concept but you have to re-find the concept by searching or opening the hierarchy to the correct branch.

**Comment by NCIEVS** [comment]
Additional info from [EHD] on the reparenting behavior, email from 3:18 PM 4/20/17:

[GF] and I wanted to confirm there is a ticket for the behavior of the Edit tab and the Navigation Hierarchy when a defined class has a parent change.
Steps and consequences:
1.	Select a defined class to reparent
2.	Make class primitive
3.	Edit parent
At this point, the Save button appears but the Description tab for the class you were editing becomes blank and the hierarchy collapses to owl:thing.
4.	Hit Save to save the new parent.
5.	The class can be found under the new parent but you have to search or open the hierarchy to find it.
6.	Then you can re-define the class if necessary, and hit Save.

This only happens when the class starts out defined and was not saved as a primitive class. If you make the defined class primitive and hit Save before editing the parent, the Description tab stays active and the hierarchy will show the class with the new parent.

**Comment by bdionne** [comment]
@hahndane @NCIEVS - I think it's also very dependent on the order of events. After making it primitive, if you delete the old parent, then add the new one, it collapses the tree to *Thing*, on the other hand if you add the new parent, then delete the old, it doesn't, it expands the tree to the new parent which then stays open after it collapses the deleted old one.

This is an artifact of Protege approach with real time edits. I'll see if I can suppress the tree updates during these operations, or at least not let the collapse occur

**Comment by bdionne** [comment]
This is fairly tricky to implement given the nature of how protege works. I think the best approach will be to keep track of the focus concept, let the events collapse the tree, and then force it open again to the same spot

**Comment by hahndane** [comment]
I think the workaround would be to save after making a class primitive but before editing the parent. 

I also wonder if adding the new parent and then removing the old parent would be a valid workaround.

**Comment by bdionne** [comment]
it will actually,  see comment above. I'm trying my idea to solve this now. I think it will work. You can teach yourself to remember the workaround but then we'll have to train everyone, so I'd like to fix it for good.

**Comment by bdionne** [comment]
This is related to #260

The good news is that a fix I'm trying works at least for this case

**Comment by rmehri** [comment]
Hi Bob,
Thanks, I have retested this fix using nci-1.0069, edit tab 0.6.5.  Please see attached snapshots for more details. 

![issue-245-1](https://user-images.githubusercontent.com/8367102/27745384-2575e692-5d91-11e7-8038-e2f76b05b04f.png)
![issue-245-2](https://user-images.githubusercontent.com/8367102/27745385-25761c0c-5d91-11e7-9f76-945282c84e2a.png)
![issue-245-3](https://user-images.githubusercontent.com/8367102/27745387-257bc418-5d91-11e7-9a5d-e8d5277cc0e3.png)
![issue-245-4](https://user-images.githubusercontent.com/8367102/27745390-25896b22-5d91-11e7-9d26-610f58c7505c.png)
![issue-245-5](https://user-images.githubusercontent.com/8367102/27745386-257776ce-5d91-11e7-8e05-e56e3272520f.png)
![issue-245-6](https://user-images.githubusercontent.com/8367102/27745388-257c491a-5d91-11e7-80d4-b690e04e2ae4.png)
![issue-245-7](https://user-images.githubusercontent.com/8367102/27745389-25877b96-5d91-11e7-898b-be9cfdc45477.png)

Thanks,
Reza
