### ISSUE TITLE
creation of dangling properties

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#264]
During testing of our processing programs we ran into:

    <rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133471">
        <P97 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A score assigned to a Curie body segment to indicate the quantity of metastases.</P97>
    </rdf:Description>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133471"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A score assigned to a Curie body segment to indicate the quantity of metastases.</owl:annotatedTarget>
        <Definition_Review_Date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2017-04-12</Definition_Review_Date>
        <Definition_Reviewer_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Thomas, Nicole</Definition_Reviewer_Name>
        <P378 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</P378>
        <P381 rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></P381>
    </owl:Axiom>

It's not fully standalone, it is related to a fully formed concept:

    <owl:Class rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133473">
        <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C20993"/>
        <NHC0 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">C133473</NHC0>
        <P106>Intellectual Product</P106>
        <P108 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Curie Extension Score</P108>
        <P370 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">caDSR General</P370>
        <P90 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Curie Extension Score</P90>
        <P95>Project: ANBL1531 Case Report Forms</P95>
        <P97 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A score assigned to a Curie body segment to indicate the quantity of metastases.</P97>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Curie Extension Score</rdfs:label>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133473"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P90"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Curie Extension Score</owl:annotatedTarget>
        <term-group rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PT</term-group>
        <term-source rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</term-source>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133473"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A score assigned to a Curie body segment to indicate the quantity of metastases.</owl:annotatedTarget>
        <Definition_Review_Date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2017-04-12</Definition_Review_Date>
        <Definition_Reviewer_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Thomas, Nicole</Definition_Reviewer_Name>
        <P378 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</P378>
        <P381 rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></P381>
    </owl:Axiom>

C133471 essentially consists of a definition, that’s it.  And this definition matches exactly what’s found in C133473.  No idea about the circumstances surrounding the creation of C133471 and then having the full concept reassigned a C133473 (or was this second create operation?).  This entity is not searchable or observable in the GUI, but we can at least flag them and clean them up during processing of the OWL file for publication.  Wait & watch to see if eventually we can prevent the creation of these guys.

**Comment by rwynne** [comment]
In the 17.05e export (5/30/17), more "dangling" properties were found at the bottom of the file:

    

    <rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134013">
        <P106>Conceptual Entity</P106>
    </rdf:Description>
    <rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134111">
        <P106>Conceptual Entity</P106>
    </rdf:Description>
    <rdf:Description rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134181">
        <P97 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">This gene is involved in the ubiquitination of protein substrates.</P97>
    </rdf:Description>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134181"/>
        <owl:annotatedProperty rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#P97"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">This gene is involved in the ubiquitination of protein substrates.</owl:annotatedTarget>
        <Definition_Review_Date rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2017-05-12</Definition_Review_Date>
        <Definition_Reviewer_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Hahn-Dantona, Elizabeth</Definition_Reviewer_Name>
        <P378 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCI</P378>
    </owl:Axiom>
</rdf:RDF>

**Comment by hahndane** [comment]
These codes appear to be failed creates of concepts. Usually, this occurs because of a deadlock during concept creation, so a concept has been assigned a code but the save hasn't been committed. These codes are no longer in the terminology but they still seem to exist in the file.

**Comment by NCIEVS** [comment]
@rwynne , do you have files lying around with these dangling properties?

**Comment by NCIEVS** [comment]
We know this is an issue, we just don't know the scenario under which it happens hence no test case.  Will keep open as "watch-and-wait".

**Comment by NCIEVS** [comment]
Perhaps enable the individuals tab (role-restricted to workflow managers) so we can search for them and delete them in the gui.  If this allows us to track their appearance, we might be able to find the source event that leads to these dangling properties.

**Comment by safrant** [comment]
There are no records written to ncievs history when these concepts are abortively created.

**Comment by safrant** [comment]
I looked through the owl files in the P5_baselines directory.  The very first file is 17.03a.  The first file where I found an annotation is 17.04c.

17.04c
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C133471">
--
That description persists for a few weeks. On 17.05c it disappears but is replaced by 3 new ones.
17.05c
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134013">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134111">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134181">
---
The next addition is 17.10d
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134013">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134111">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134181">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C135086">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C140656">
---
And another on 18.02d
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134013">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134111">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C134181">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C135086">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C140656">
<rdf:Description   rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C146911">
---
There have been no additions or removals since then.

**Comment by NCIEVS** [comment]
Note, the "individuals by class" doesn't pick up these guys.  Tested with the entities above.

**Comment by NCIEVS** [comment]
Per @safrant , this hasn't occurred in a number of releases and currently no danglers.  closing ticket.
