### ISSUE TITLE
data being stored in xml:lang attribute

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#287]
Observed xml:lang's below, operation leading to this hasn't been identified yet.

C113504=FULL_SYN: IGH
```
        <P90 xml:lang="-maf translocation">IGH</P90>
        <P90 xml:lang="/maf translocation">IGH</P90>
```
C113512=FULL_SYN: IGH
```
        <P90 xml:lang="-crlf2 fusion gene">IGH</P90>
        <P90 xml:lang="/crlf2 fusion gene">IGH</P90>
```

**Comment by NCIEVS** [comment]
This turns out to be a content issue.  A property value has an @ within.  Not sure of the best way to escape this chars (e.g. &commat; or &#64; or ...).  Perhaps the gui can display the @ and in the background store it escaped.  For the time being, we'll see if we can spell it out in the property value as "at".

**Comment by bdionne** [comment]
It sure looks the `OWLConstantEditor`, which breaks out the type and language into separate combo boxes, but also parses the value, is not escaping correctly according to the spec:

https://www.w3.org/TR/owl2-syntax/#Literals

Notice in edittab, that if `FULL_SYN` values contain `@` it works fine, I think because the default `OWLLiteral` is `OWLLiteralString` or at least appears to be. We type that value as a text area. 

Needs more investigation but I think we'll need to be careful about getting rid of all the types

**Comment by NCIEVS** [comment]
Revisit to see where the bad code is.

**Comment by singhik** [comment]
@bdionne :: Hello, If you could please share the subroutine where the fix was applied and what the fix was , in terms of functional area ? as in , trying to get idea for what was changed from prior, f.e. if special characters were type casted into string f.e. if '@' for all Complex property will be read as 'at'  etc ?

@NCIEVS :: Hello,  My Use cases for this requirement thus far are testing allowed special characters f.e. @ for all Complex property values(ALT_DEF,DEF ,FULL_SYN) and then check for xml:lang exceptions, my questions are ::

>Where do i check for <xml:lang> exception messages ? what will be the Exception message verbiage ,as in how to identify the Exceptions in XML tag while manual parsing ?
>Are there any other Use Cases per your valuable input ?

**Comment by NCIEVS** [comment]
I don't recall, but I don't think there is an exception. It's a data corruption issue.  If you create an annotation, let's say an editor_note, and include the @ in the value, e.g. "POC for authority is joe@here.com", anything following the @ is treated as a language identifier and the value becomes "POC for authority is joe".

**Comment by singhik** [comment]
@NCIEVS : Hi, I would require the list of special characters which might cause corruption issues like @ and how were they type-casted in code to handle, as in they will be omitted in value and every text after that  ?
Secondly, i tried creating an annotation with @ but it was not escaped but the value got saved with @ and the text after that, please find below the screen print ::

![image](https://user-images.githubusercontent.com/36314371/42654095-69ee5d4a-85e5-11e8-97dc-71de15bb7ff4.png)

**Comment by bdionne** [comment]
@singhik - yes this was a low level [change](https://github.com/NCIEVS/owlapi/commit/b2ab5d21d29dac1ea745ff6397cefabd0de91fc8) in the OWL API. As you can see what we did was disable the code that interprets the `@` char as a language attribute. Even is one escapes it the various parsers, exporters, etc.. don't clearly handle it. 

The examples above at the top of the ticket show what was happening when users occasionally have a `@` in the preferred name. So to test it create some props with it and see that the `@` persists as well as the chars after the `@`

We're going to revisit this, probably soon, when we upgrade to OWL API 5, though there's been quite a discussion in the forums, etc. as I think this is really an RDF issue.

**Comment by singhik** [comment]
@NCIEVS : Hello,  from Bob's explanation , it appears to be for the special characters like @ to exist and texts after those as well instead of getting omitted , please second ?

**Comment by NCIEVS** [comment]
Yes, this fix is specific for the @ character.

**Comment by singhik** [comment]
@NCIEVS  :: Hi , QA has verified below scenarios :: 

1. Creation of Complex properties (DEF,ALT_DEF,FULL_SYN) with 'value' having '@' , the creation was successful and the @ was displayed as-is and the texts after @ were also displayed as-is, post creation .

2. Creation of Annotation Properties (Sibling and Sub) with 'value'  having  having '@' , the creation was successful and the @ was displayed as-is and the texts after @ were also displayed as-is, post creation .


Please review and second screen prints for coverage validation ::

Complex Properties :: 

![image](https://user-images.githubusercontent.com/36314371/42832420-2523aee4-89bf-11e8-9491-b6f08158ace5.png)

Annotation Properties ::

![image](https://user-images.githubusercontent.com/36314371/42832444-39dd9836-89bf-11e8-9394-e42199dd905f.png)

![image](https://user-images.githubusercontent.com/36314371/42832456-45e5ba82-89bf-11e8-9848-45ecaff85ee1.png)
