### ISSUE TITLE
export of referenced entities by display property or by IRI

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#321]
Applicable to superclasses, class restrictions and "associations" (properties that have xsd:anyURI in the range).  The current ReportWriter spreadsheet export will output the IRIs of the referenced classes.  The feature request is to have the option (perhaps selected by the Preferences display options) of outputting the referenced classes using their rdfs:label or selected display property.

**Comment by NCIEVS** [comment]
The code to display the superclasses with labels rather than IRIs is already in there.  Maybe the same code can be used to display the labels of the other referenced entities.  Haven't checked, but I imagine class restrictions are already covered, so this ticket might only need to deal with the "associations".

**Comment by bdionne** [comment]
Not sure which code you're referencing, the classic report option (tree view) uses the display name. The other two report types (spreadsheet export) use the code in the lucene export facility, and have an option when you configure them, `Use current rendering instead of IRIs`, which will give you whatever is set in the preferences.

Or at least it does for me, I completely reworked all this recently and may have a newer version

**Comment by bdionne** [comment]
The only case not working is associations when the user doesn't select current rendering

**Comment by singhik** [comment]
@NCIEVS : Hello, i have performed four scenarios per below, i am not able to differentiate between 'Render by prefixed name'  and 'Render by prefixed annotation pty' as their Export results are same in sense of their value and appearance. The functionality of the Checkbox 'Use existing rendering instead of IRI' while Export using LQT   works fine . 

Please review below scenarios and screenshots ::

Scenario 1> 

Render option selected is ‘Render by prefixed name’ and then doing Export Report Writer by checking box ‘Using current renderer instead of IRI ‘ 

![image](https://user-images.githubusercontent.com/36314371/44932002-acdd7f00-ad31-11e8-9406-6962df4fe62a.png)

 Export Results : 

![image](https://user-images.githubusercontent.com/36314371/44932030-c1217c00-ad31-11e8-88de-d5cf8e27aff0.png)


Scenario 2>

Render option selected is ‘Render by annotation property’ and then doing Export Report Writer by checking box ‘Using current renderer instead of IRI ‘ 

![image](https://user-images.githubusercontent.com/36314371/44932055-d7c7d300-ad31-11e8-83e3-512da16fa37a.png)

Export Results : 

![image](https://user-images.githubusercontent.com/36314371/44932067-e615ef00-ad31-11e8-9f08-7340df0e168c.png)


Scenario 3>

Render option selected is ‘Render by annotation prefix’  and then doing Export Report Writer by checking box ‘Using current renderer instead of IRI ‘ 

![image](https://user-images.githubusercontent.com/36314371/44932080-f6c66500-ad31-11e8-9200-1bf6d0e05b34.png)

Export Results : 

![image](https://user-images.githubusercontent.com/36314371/44932092-004fcd00-ad32-11e8-99d5-02fa3efdedaf.png)


Scenario 4>

Render option selected is ‘Render by annotation pty’  and then doing Export Report Writer by NOT checking box ‘Using current renderer instead of IRI ‘ 

![image](https://user-images.githubusercontent.com/36314371/44932107-13629d00-ad32-11e8-9660-0ed0a38d7517.png)

Export Results : 

![image](https://user-images.githubusercontent.com/36314371/44932122-1d849b80-ad32-11e8-8c91-911322017141.png)

**Comment by singhik** [comment]
@NCIEVS : QA has validated attached scenarios , Export Report Writer works fine, please second so that this ticket can be closed :: 


[Issue 321_New.docx](https://github.com/NCIEVS/nci-protege5/files/2361787/Issue.321_New.docx)

**Comment by NCIEVS** [comment]
Seconded, looks good.

**Comment by singhik** [comment]
Thanks @NCIEVS ...
