### ISSUE TITLE
Tag-1.0083-Unchecking and Re-enabling NCI Edit Tab Plugin the Contents of Plugin Not avaliable 

### ISSUE THREAD

**Issue by rmehri** [NCIEVS/nci-protege5#326]
Steps to reproduce:
1.	Launch server and client
2.	Log into local host http://localhost:8080 (Used Workflow Manage and Modelerr), nci-10083
3.	Select NCI Edit Tab and click X or uncheck to remove this plugin from protégé page.   
4.	Go back to Window/Tab and reselect NCI Edit Tab plugin, then it became black 
5.	The NCI Edit Tab shows blank and refresh the User Interface did not help. 
6.	If you log out and log back into the protégé then it comes back. 
7.	The same behavior occurs when using QA server: https://nciws-q791-v.nci.nih.gov:9090
Please see attached screenshots for more detail.

![disabling nci edit tab plugin-](https://user-images.githubusercontent.com/8367102/30441512-ab72b40e-9947-11e7-8193-4eb463d34bab.png)

Thanks,
Reza

**Comment by singhik** [comment]
@bdionne : Hi Bob, this behavior if i understand correctly is w.r.t  Selection and de-selection of tabs from 'Window->Tabs->NCI Edit Tab' .    When a user de-selects it and then re-selects , the 'NCI Edit Tab' **does show up on the console but is not-usable as is blank** , so to conclude, if a user de-selects 'NCI Edit Tab' from 'Windows->Tabs'  ,then the only way to get a working 'NCI Edit Tab' is to logout /re-login  or Restart Protege Client ...

Please align if this is the expected behaviour ....

**Comment by bdionne** [comment]
@singhik - that's correct, pretty much, though if you logout/login again it might work. However the best bet for now is to just stop/restart the app. Hopefully users aren't doing this a lot, there's no reason to. 

This will likely get more attention in the next round when we'll be looking into login issues more. That's why I didn't put this on the QA queue yet.

**Comment by singhik** [comment]
Thanks Bob, will move it to Future Release Milestone as Low priority

**Comment by singhik** [comment]
@bdionne : Hi Bob, apparently it does not work now without a restart as well, please find below ::

NCI Edit Tab ,when Selected :: 

![image](https://user-images.githubusercontent.com/36314371/51141729-1315fa80-1818-11e9-8754-d857c84e0013.png)


Deselecting NCI Edit Tab from Windows Tab ::

![image](https://user-images.githubusercontent.com/36314371/51141789-2628ca80-1818-11e9-9a5b-2d8f3f5d5a62.png)


Reselecting NCI Edit Tab from Windows Tab, does show NCI Edit Tab **but is blank** ::

![image](https://user-images.githubusercontent.com/36314371/51141828-3f317b80-1818-11e9-882e-7986994faf8a.png)

**Comment by bdionne** [comment]
fixed opportunistically, moving into next release

**Comment by singhik** [comment]
Working fine ,closing the ticket .........
