### ISSUE TITLE
ReportWriter spreadsheet doesn't report restrictions in a defined class

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#380]
If the class is primitive, the restrictions are reported.  However, in a defined class, superclasses are reported but the restrictions in the class expression are not.  This doesn't happen in the "tree" report, it only happens in the "spreadsheet" report.

From [EHD]:
"I had some new codes that I ran a report for and wanted to see all of the filler values for the roles and associations on these concepts. Here is the text file generated from that report and an excel file. The first four concepts are defined in protégé and there is no values in columns T and AA because the report writer cannot disambiguate the roles in the Equivalent To role group. However, it is able to get the parents from the Equivalent To role group (column B). The last 3 concepts in the report are primitive and you can see role filler values in column AI."

The (tab-delimited) text file mentioned above is attached.
[DLBCL_new_concepts_report.txt](https://github.com/NCIEVS/nci-protege5/files/1939914/DLBCL_new_concepts_report.txt)

**Comment by bdionne** [comment]
@hahndane Do we have an example of this, they seem to work for me. Is it when the object restrictions are embedded in a definition?

**Comment by singhik** [comment]
@NCIEVS :: Hello, I would need certain clarifications w.r.t. this requirement, please provide your valuable insight to below :::

**1.** I chose two 'defined' classes (C21423,C21415)  and one 'primitive' class (C21422) , i did an Export using an Input File option, and choose two properties aka 'Gene_Product_Encoded_By_Gene' and 'Gene_Product_Has_Biochemical_Function',, after Export i see both defined classes and primitive class restrictions reported  which are defined in 'Equivalent To' section of 'Description' Tab only .
**question>**Does this mean 'restrictions' by definition are only those which appear under 'Equivalent To' tab ? 

Below shows Export results ::

![image](https://user-images.githubusercontent.com/36314371/51273117-eee22700-1999-11e9-8166-98a5bcb9f25f.png)


Primitive Class ::

![image](https://user-images.githubusercontent.com/36314371/51273274-5009fa80-199a-11e9-9c7f-d3874091b444.png)

Defined Classes ::

![image](https://user-images.githubusercontent.com/36314371/51273290-5a2bf900-199a-11e9-8c4e-63d65fb2247d.png)


![image](https://user-images.githubusercontent.com/36314371/51273304-61eb9d80-199a-11e9-8ee4-0e48234c9d4a.png)


**2.**   While doing an 'Export' via 'ReportWriter', user has to always chose Properties for Export, f.e. if there are 20 properties defined in restriction, all have to be manually selected for Export, 
**question>** Why not all the restrictions which are defined for the Class(and its immediate children) should be exported by default ,instead of having to select all properties of a restriction ?

Below, i do not select any property and the Export only shows Class and Sub Class without any restrictions on properties :: 

![image](https://user-images.githubusercontent.com/36314371/51273667-50ef5c00-199b-11e9-831a-32458819e224.png)

![image](https://user-images.githubusercontent.com/36314371/51273715-682e4980-199b-11e9-8c5c-3675e3267704.png)

**Comment by NCIEVS** [comment]
Hi @singhik , 

> Does this mean 'restrictions' by definition are only those which appear under 
> 'Equivalent To' tab ?
Yes, the restrictions of a defined class show up in the "equivalent" class section.

>  Why not all the restrictions which are defined for the Class(and its immediate children) 
> should be exported by default ,instead of having to select all properties of a restriction ?
Hmm, good question.  This feature to select all restrictions of a class by default has not been requested.  Usually people generate reports on only a few properties at a time, "do my classes x, y, and z have properties (or restrictions) a, b, and c"?  so perhaps this use case for restriction defaults has never come up.

On the other hand, it looks like the report of restrictions on defined classes is working now.  Thanks!

**Comment by singhik** [comment]
Thanks @NCIEVS ....
