### ISSUE TITLE
Scroll Down Tab For  Lucene Search Erroneously Shifts Navigation Control To First Page

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#414]
**Work-Flow::** "Lucene Search Tab" when searched with a Query fetching results in Multiple Pages .

**Issue ::** When navigating to pages(f.e. second page) and the right Scroll Tab is clicked for scrolling, the navigation controls jumps back to page 1 .

This also happens if i use 'up' and 'down' keyboard keys  for navigation instead of Scroll Tab. 

**Screen Prints for Reference ::**

Query showing multiple search:

![image](https://user-images.githubusercontent.com/36314371/52737054-660adb00-2f99-11e9-9f10-57d4d72595df.png)

Navigating to Second Page : 

![image](https://user-images.githubusercontent.com/36314371/52737144-a407ff00-2f99-11e9-996b-ae0208deaa52.png)

Using Scroll Tab for scrolling down,  the controls goes back to Page 1 

![image](https://user-images.githubusercontent.com/36314371/52737182-b5e9a200-2f99-11e9-87e2-724cfe67b72d.png)

**Comment by bdionne** [comment]
nice catch @singhik - this is fixed in the next [plugin update](https://github.com/NCIEVS/lucene-search-tab/releases/tag/lucene-search-tab-1.2.2)

**Comment by singhik** [comment]
Thanks @bdionne  .

@safrant :: Hello, This issue is fixed in 'Lucene Search Tab 1.2.2', the plugin jar is available at URL posted (have posted to your jabber), Please update the repository for auto-plugin which Business(Editors) use and do let me know once done .

@NCIEVS : Hello, Post Tracy's update, you may please publish it to the Editors for the issue being fixed in Lucene Search Tab and is available in the auto-plugin repository (One thing which i am not sure if needs be aligned is, post auto-update of a latest version, the old plugin also remains, unless deleted manually from plugins folder, so if Editors are not aware of the same, we can align them on that cosmetic issue which is due to get fixed in next release). 

I will keep this ticket open ,in resolved and in QA bucket,so that i can regression test in the next client code base for Milestone Release.

**Comment by NCIEVS** [comment]
Thanks!  @singhik , @safrant , yes, it looks like after the autoupdate the old jar remains in place.  Probably advise the editors how to manually delete the old jar.

**Comment by bdionne** [comment]
yea, it’s definitely a windows only issue, at least on this MAC it works. I can see in the stack traces of the error that it can’t move the old jar because some process is holding onto the file :(

**Comment by safrant** [comment]
It didn’t remove the old jar from my Mac because the name of the jar was changed to drop the “SNAPSHOT” suffix


2019-02-14 17:21:12.147 [Installing plugins thread] INFO  PluginInstaller    The NCI Lucene Search Tab plugin has been downloaded to /var/folders/gw/r1cv_zwj1x776nmb88pcfqj1zl05ld/T/lucene-search-tab5165964675281259746.jar

java.nio.file.NoSuchFileException: /Users/safrant/EVS/Protege/nci-protege-V3.0.0/plugins/lucene-search-tab-1.2.1.jar

       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)

       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)

       at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)

       at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)

       at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)

       at java.nio.file.Files.move(Files.java:1395)

       at org.protege.editor.core.update.PluginInstaller.moveExistingPluginToBackupLocation(PluginInstaller.java:183)

       at org.protege.editor.core.update.PluginInstaller.copyPluginToInstallLocation(PluginInstaller.java:195)

       at org.protege.editor.core.update.PluginInstaller.install(PluginInstaller.java:104)

       at org.protege.editor.core.update.PluginInstaller.lambda$run$0(PluginInstaller.java:63)

       at java.lang.Thread.run(Thread.java:748)




NCI-01870878-ML:nci-protege-V3.0.0 safrant$ pwd

/Users/safrant/EVS/Protege/nci-protege-V3.0.0

NCI-01870878-ML:nci-protege-V3.0.0 safrant$ ls plugins/

evs-history-1.0.4-SNAPSHOT.jar          metaproject-admin-1.0.2-SNAPSHOT protege-client-3.0.1-SNAPSHOT.jar

lucene-search-tab-1.2.1-SNAPSHOT.jar    metaproject-admin-1.0.2-SNAPSHOT.jar    protege-server-3.0.1-SNAPSHOT.jar

lucene-search-tab-1.2.2.jar             nci-edit-tab-0.9.5-SNAPSHOT.jar         revision-history-1.0.9-SNAPSHOT.jar

metaproject-1.0.0-SNAPSHOT.jar          pellet-protege-2.4.1-SNAPSHOT.jar sparql-query-plugin-2.1.1-SNAPSHOT.jar



Tracy M. Safran
Programmer Analyst - EVS support
Frederick National Laboratory for Cancer Research

Ph: 240-276-5172
Tracy.Safran@fnlcr.nih.gov<mailto:Tracy.Safran@fnlcr.nih.gov>

**Comment by bdionne** [comment]
It won’t if the original was installed with the SNAPSHOT suffix, .eg. if you preinstalled them on your machine.

When it downloads it removes the -SNAPSHOT, so when going form 1.2.1 -> 1.2.2 it will look to delete something with 1.2.1.jar and not find it.

If it’s install correctly from the autoupdate, onto a MAC it should work. You can test by just renaming your 1.2.1-SNAPSHOT to 1.2.1.jar

**Comment by singhik** [comment]
@NCIEVS  @bdionne  :: Hello , please find below the Use Case results, need clarification on the requirement  here ::

1. Scroll Function using Mouse and Keyboard **DOES NOT**  jump the search page from nth to first --- As Expected 

2. Scroll Function using both Mouse Scroll and Keyboard Up and Down Keys  is **DISABLED** now, which means to navigate forward or backward ,it can only be done using '>' and'<' buttons at the top of Lucene Search Panel .---- Was the Requirement to freeze Mouse and Keyboard Scroll options for navigation  , please clarify ? 

3. Auto update of Plugins ,does not Overwrite the Old Plugins,in Windows ---- Should i create a separate ticket for this or should this be handled as part of this Issue ? 

![image](https://user-images.githubusercontent.com/36314371/58064710-3bf52600-7b51-11e9-92dd-94423ef0d406.png)

**Comment by bdionne** [comment]
@singhik I'm not sure what the issue is? The scroll bar and the up/down arrows scroll within a page. So for example on my small screen 50 results are shown on each page and I have to scroll down to see them all.

The '>' and '<' buttons do the paging. 

Was it different before? The bug, which I think is fixed, was that if there were multiple pages when you clicked the '>' button it would go back to the 1st.

**Comment by singhik** [comment]
@bdionne : Hi Bob,  please find below the series of this issue : 

1. The issue was the Scroll Option using Mouse Scroll, Keyboard Up Down Keys and > < buttons would take the control from nth page to first page instead of (n-1)th Page .

2. The issue is resolved now w.r.t navigation from nth Page to (n-1)th page using > < buttons .

3.However, using the Mouse Scroll and Keyboard Up Down keys, one can not navigate from any page to any other page, Mouse Scroll and Keyboard Keys seem to work only within a page instead of navigation across pages. 

Hence, I am not sure if the Editors want Mouse Scroll and Keyboard Keys  to be usable for navigation across pages as well. If not, I am good to close this ticket .

**Comment by NCIEVS** [comment]
Oh, I see.  OK, no, I think keyboard & mouse are only for navigation within the scrollable area. For pagination, it should be the < and > buttons at the top of the panel.

**Comment by bdionne** [comment]
I see, thanks @singhik. Yea, I'm not sure how it worked before, maybe the left right arrows ought to page?

**Comment by bdionne** [comment]
ah, ^^ I'm ok with that too :)

**Comment by singhik** [comment]
Thanks @NCIEVS @bdionne .
Issue retested on 3.1.0 Protégé Client, works as Expected hence closing it .
