### ISSUE TITLE
NCI Edit Tab does not work functionally if closed and reopen 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#416]
Hello, 

1. Login to Protege Client 3.1.0 , for the first time login 'NCI Edit Tab' is not displayed by default, Select 'NCI Edit Tab' from 'Windows->Tabs', the 'NCI Edit Tab' gets displayed but is Empty and non-functional .

2. Restart Protege Client and re-login, Client displays 'NCI Edit Tab' and is functional  but close the 'NCI Edit Tab' and reopen , the 'NCI Edit Tab' displayed is Empty and Non Functional .

Screen prints for the issue are below :

'NCI Edit Tab' is displayed and is functional when we restart Protege Client : 

![image](https://user-images.githubusercontent.com/36314371/58041985-776b0280-7b07-11e9-99d9-0dce8d7df838.png)

Closing the 'NCI Edit Tab'  and reopening, the displayed 'NCI Edit Tab' is blank  :: 

![image](https://user-images.githubusercontent.com/36314371/58042055-a6817400-7b07-11e9-9d80-344444d3cf0c.png)

**Comment by singhik** [comment]
This issue is duplicate of #326 ,hence closing this thread

**Comment by bdionne** [comment]
yea, we have a ticket for this. It's annoying, a similar issue occurs when you use the Admin panel and then restart the app and login and open a project. The problem arises because we have rules that govern which users can use which panels, which panels are the defaults, and we also track which panels were opened by a user so they can be re-opened on subsequent restarts. These conflict a bit and need to be sorted out.
