### ISSUE TITLE
Batch Edit For Simple Property and Complex Property Fails

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#420]
Issue 1 > When Performing a Batch Edit for Simple Property (f.e. P108 ) Preferred Name, Protege Throws  '‘Exception caughtjava.lang.NullPointerException'   on Windows 10 .

Issue 2 > When Performing a Batch Edit for Complex Property (f.e. P90) Full Syn , New and Modify operations fail .

Attached are Batch Edit Files for Simple Property and for Complex Property which are used for performing Batch Edits .

[Batch Edit_Complex Pty.txt](https://github.com/NCIEVS/nci-protege5/files/3315045/Batch.Edit_Complex.Pty.txt)
[Batch Edit_Simple Pty.txt](https://github.com/NCIEVS/nci-protege5/files/3315047/Batch.Edit_Simple.Pty.txt)

**Comment by singhik** [comment]
@bdionne  : Hello , 

1. For Batch Edit Simple Property :: 

I used the attached file for performing a Batch Edit Simple Property f.e. Preferred Name (P108), the Batch Edit went fine without an Exception but the Dialog Prompt for 'Committing Changes' to Server remains forever , Close and Cancel button do not work, Protege Hangs and has to be restarted. Have tried this multiple times and behaviour remains same .

Screen Shot ::

![image](https://user-images.githubusercontent.com/36314371/59957870-e7a0d700-946b-11e9-9dff-53faead6bf0c.png)

**Comment by bdionne** [comment]
@singhik - thanks, @NCIEVS and I saw that too when triaging. I'm pretty sure the issue is that when the input file is very small, one or two records, the process finishes so quickly that the progress bar updates get out of sync somehow. I'll investigate it.

For the second complex edit example, the file you uploaded is not quite right. The format is a little more involved. I'm attaching an example we also used yesterday to triage the other failure. It turns out that we are *not* going to allow the modeler to update the `NCI/PT` `Full_Syn` using the complex editing batch. Instead they will us e a simple edit of `Preferred_Name`(`P108`). This will suffice because whenever you edit this, the `NCI/PT` `Full_Syn` is synced to match it. The reason for this is that the rules governing these properties are more complicate and in batch we don't have all the instances available as we process each record.

But you can use this example as a model to test other complex properties on your test suites.

The newest 1.0.1 plugin I pushed for `EditTab` fixes the null pointer issue, related to a datatype missing in the QA content, which is why I didn't see it locally.

**Comment by bdionne** [comment]
[v5.testFullSynSingleChange.txt](https://github.com/NCIEVS/nci-protege5/files/3316686/v5.testFullSynSingleChange.txt)

**Comment by NCIEVS** [comment]
Note to self @NCIEVS , still need to add test files for the regression testing, successful & failure tests.

**Comment by singhik** [comment]
@bdionne : Hello Bob ,
I tried doing Edit Simple Pty via Batch and Protege is unable to commit changes to the server, the 'Commiting Changes' Pop up remains for ever and Cancel button does not work to close it . Protege has to be restarted in order to bring it back as operational . 

![image](https://user-images.githubusercontent.com/36314371/61212260-b9f82800-a6cf-11e9-85e6-3fc404c50983.png)



@NCIEVS : Hello , If you could please clarify below requirement : 

1. Complex Property Edit for 'FULL_SYN'  will not be allowed  . 
2. Complex Property Edit for 'DEFINITION' and 'ALT_DEFINITION' will also be not allowed  ?
3.  Please share few sample files for Complex Batch Edit types for which i can use as a sample to create my Batch files, when i am doing it from 'https://github.com/NCIEVS/nci-protege5/wiki/batch-edit-formats' , it does not compile, i have attached my sample (which does not compile) for Batch Edit hence does not work . 

[Batch Edit_Complex Pty.txt](https://github.com/NCIEVS/nci-protege5/files/3392004/Batch.Edit_Complex.Pty.txt)

**Comment by NCIEVS** [comment]
Hi @singhik 
1- The full_syn complex property batch edits are allowed, but not in all cases.  Batch edits of full_syns where the term source is NCI and the term type is PT are not allowed.  To edit these full_syn values the user should edit instead the preferred_name property.
2 - the batch edits of definition and alt_definition are allowed.
3 - working on it, will have to do it in batches.  I have simple-property edits ready to go.

**Comment by NCIEVS** [comment]
test batch edits of simple properties, run in the order below so that edits are reversed:
1) success
2) reverse
3) failure

[simple-props-success.txt](https://github.com/NCIEVS/nci-protege5/files/3408911/simple-props-success.txt)

[simple-props-revert.txt](https://github.com/NCIEVS/nci-protege5/files/3408912/simple-props-revert.txt)


[simple-props-fail.txt](https://github.com/NCIEVS/nci-protege5/files/3408913/simple-props-fail.txt)

**Comment by singhik** [comment]
@NCIEVS : Hello, Thanks for Batch Files for Simple Pty, actually i had the Batch Files for Simple Pty but not for Batch Edit Complex Pty. As there are multiple flows , i  hence prepared below table for clarification on the completed flows, the failed ones and the ones needing a batch file to validate as mine does not compile ::

![image](https://user-images.githubusercontent.com/36314371/61532304-65b6b600-a9f7-11e9-8543-fc97f7e4b986.png)

**Comment by NCIEVS** [comment]
Hi @singhik , Ah, OK, let me do the complex ones.  The BatchEditSimplePty is probably wedging because it runs too fast.  You can use the the simple-props-success.txt (and the rest) that I posted above to validate simple property batch edtis.  I'll do for the complex props what I did for the simple props, a success and a failure case, as well as a reversal.

**Comment by NCIEVS** [comment]
Hi @singhik , here are the success and the reversal batch edits of complex properties.  I'll put the failure case later (and edit this comment).

[complex-props-success.txt](https://github.com/NCIEVS/nci-protege5/files/3412986/complex-props-success.txt)

[complex-props-revert.txt](https://github.com/NCIEVS/nci-protege5/files/3412987/complex-props-revert.txt)

**Comment by singhik** [comment]
@NCIEVS : Thanks for the file samples, now the only Batch Edit/Load that is failing/wedging  for me is 'Batch Edit Simple Pty', all others  work fine. Not sure, why only 'Batch Edit Simple Pty' is wedging and fails to commit changes to Server while others work . Below is the updated table with latest results. 

![image](https://user-images.githubusercontent.com/36314371/61572435-9afceb80-aa6b-11e9-8288-1671165c0c24.png)

**Comment by NCIEVS** [comment]
@singhik the 'Batch Edit Simple Pty' is a small job and runs too fast.  Try the [simple-props-success.txt](https://github.com/NCIEVS/nci-protege5/files/3408911/simple-props-success.txt) instead (from my comment above).

**Comment by singhik** [comment]
@NCIEVS : Hello,  'simple-props-success.txt'  did work when used as-is  but i created my own file with 20 records but have not been able to successfully commit the changes to Server.  

I would rather have this ticket open until the small file upload for 'Batch Edit Simple Pty' works . For the Release on Monday we can publish a release note to Editors of file size < 20 having intermittent wedging with 'Batch Edit Simple Pty' ....

**Comment by NCIEVS** [comment]
@singhik , OK, agreed.

**Comment by singhik** [comment]
Batch Edit Simple Pty is working fine as expected alongside other Batch Edits, hence closing the ticket ....
