### ISSUE TITLE
sparql plugin enhancement - timeout on long queries

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#432]
Currently a query can continue running for a long time (maybe not even terminate), for whatever reason, low memory, query complexity, and protege needs to be terminated with control-C on terminal.  Would be very good to have a timeout for sparql queries, default 5 mins, but user-adjustable if possible.

**Comment by NCIEVS** [comment]
Example non-terminating query in #435 .

**Comment by singhik** [comment]
@NCIEVS  : Hi, 

1. SPARQL Endpoint defaults to a timeout of 30 Seconds , it is indeed User Adjustable . 
2. Keyboard operation of CTRL + C ,does **not** terminate a long Query but entire Protege Client , Query gets terminated post default timeout exceeds .  Exception Error  Log & Message dialog  box are pasted below for review .
3. The need of CTRL +C is redundant because the Default timeout set is doing that inherently & is user configurable f.e. when  kept at 5 Seconds(or any other user desired value), the Query automatically terminates when Execution Time Exceeds Default Timeout .

As per me, this ticket is good to close, please review and advise if other wise .

![image](https://user-images.githubusercontent.com/36314371/118045387-d5710000-b345-11eb-85e0-46869bfa7111.png)

![image](https://user-images.githubusercontent.com/36314371/118045417-de61d180-b345-11eb-9d86-4aa34bcc0475.png)
