### ISSUE TITLE
Protege Locks when Two Editors are Working in the Same (Sub)Branch

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#440]
@bdionne  :: Hello, 

Logs and Notes from Editors :: 

""this may only occur when the modeling is edited and not for other edits. Editors cannot remember what kind of batches we tested but most batches are not parenting/modeling edits (except for loads, which Editors think they tested but  don’t remember how many versions have been released since then). Editors think the times Editors  have experienced this freeze, parents or modeling were edited. Editors will note that it didn’t have the classifier running during the documented freeze, so they don’t think the classifier is involved.""

""Editor have had this happen to her today when she was reviewing some items for other Editors .Editors had them look at some data she had just added to the Medical Device branch. they had few suggestions, while they made the changes, she was still focused in the same branch (but not directly on the concepts she was working on), when Editors was editing, her instance froze (see thread dump below). This is something she has had happen to her before and other Editor noted that he had protégé freeze when he is discussing editing with Al. She had just never captured the thread dump before.""

[Logs_Editors.txt](https://github.com/NCIEVS/nci-protege5/files/4350525/Logs_Editors.txt)

**Use Cases Executed by QA ::**

**Use Case 1 ::** Two protégé client Instances , both instances on the same concept/Branch, performing Batch Load/Edit on one instance and doing other non-batch operations(f.e. Property Delete/Edit operations) on another instance  . 

**Actual Result ::** Both instance and operations work successfully without hanging .

**Use Case 2 ::** Two protégé client Instances , both instances on the same concept/Branch, performing Batch Load/Edit on one instance and doing other batch Load/Edit on another instance  . 

**Actual Result ::** First Batch Load/Edit operation works but after initiating Batch Load on second Instance, Protégé Instance hangs indefinitely . However , I do not see Command Console showing any error logs as Editors gave below .

**Use Case 3 ::**  Two protege client instances, one instance is locked on a Concept/Branch, other instance is performed with operations and re-tree of parents of the same Concept/Branch , the re-treeing of parents go down 3-4 level in hierarchy . After completion, the first instance should receive the edits done in the second instance and no freeze or hang should happen .

**Actual Result ::** Edition and updation happened in both instances without freeze and hanging in couple of trials. This use case will be done multiple times across multiple hiearchy to validate the freeze 

[Testing Multiple Batch Loads&Edits On Same Branch.docx](https://github.com/NCIEVS/nci-protege5/files/4350771/Testing.Multiple.Batch.Loads.Edits.On.Same.Branch.docx)

**Comment by bdionne** [comment]
Will take a look, at a glance it looks to be the usual autoupdater thread.

**Comment by hahndane** [comment]
These freezes have occurred when one editor is focused and/or navigating in one subbranch while another editor is manually modifying parents in that same subbranch. (Batch edits were not involved.) Please add this test scenario.

**Comment by hahndane** [comment]
These freezes have occurred when one editor is focused and/or navigating in one subbranch while another editor is manually modifying (1 or more) parents in that subbranch.  (Batch editing was not involved.) Please add this testing scenario.

**Comment by singhik** [comment]
@hahndane : Hello, added as Use Case 3 in above thread .

**Comment by bdionne** [comment]
I can reliably reproduce one of these reported freezes, using a smaller ontology and a somewhat contrived setup. We've know all along that the issue is the extremely long path length of the code in the autoupdater.

I have a possible fix which will be in the next protégé build. It's not a real solution but is worth a try if it stops the freezes.

**Comment by bdionne** [comment]
fixed in 3.4.0-dev1 tag

**Comment by NCIEVS** [comment]
Another instance of this issue from [EHD]:

- Which operation failed? (such as Merge, Copy, Creation, PT changing)
Protégé GUI Froze while working in the same branch as [GC] (I had deleted a concept that he had created because it was a duplicate of an existing concept.)
- Approximately what time did this failure occur? 
On Wednesday, July 8 Between 9:20 and 9:30 am
- Description or sequence of steps followed:
[GC] and I had each been reviewing the C28193 Syndrome and the C85865 X-Linked Inherited Disorder sub-branches. Because a concept [GC] created the day before C173467 was a duplicate of C125665. I had [GC] refocus on a different branch and then I deleted C173467 using the Entities tab. Afterward, I was able to refocus on a different branch, while [GC] made some edits to C125665. Several minutes later, when I thought [GC] was done editing, I navigated back to C125665 to take a look at what he had done. Then my GUI became unresponsive.
- Outcome (screen frozen, concept not created, had to log out and in to get things to work better):
GUI froze. I had to close the protégé dos window and log back in.
- Attach log if possible (current Protégé folder, in  .protege, logs):
[protege20200713-lh.zip](https://github.com/NCIEVS/nci-protege5/files/4927030/protege20200713-lh.zip)

Info from the log, no ERROR and only a WARN is in the session, about 5' before the log for the session ends:
- start of log for the session, 2020-07-08 09:07:21.406
- 2020-07-08 09:25:13.201 [AWT-EventQueue-0] WARN  OWLOntologyManagerImpl    BADLY BEHAVING LISTENER: null has been removed
java.lang.NullPointerException: null
	at org.protege.editor.owl.ui.frame.cls.OWLClassGeneralClassAxiomFrameSection.isResettingChange(OWLClassGeneralClassAxiomFrameSection.java:101) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
	at org.protege.editor.owl.ui.frame.AbstractOWLFrameSection.processOntologyChanges(AbstractOWLFrameSection.java:91) ~[protege-editor-owl-5.1.2-SNAPSHOT.jar:na]
- end of log for the session, 2020-07-08 09:30:00.981 

No thread dump was done for this instance of the "concurrent browsing" freeze.

**Comment by bdionne** [comment]
It would be great to try sonme of these scenarios with the new tag and see if that solves it

**Comment by singhik** [comment]
@bdionne : Hi, Protege Client Instances hangs when 'Two or more protégé client Instances , both instances on the same concept/Branch, performing Batch Load/Edit on one instance and doing other non-batch operations(f.e. Property Delete/Edit operations) on another instance .' 

Batch Load/Edit operation hangs on "Committing Changes to the Server' and 'Cancel' button also does not kill the operation, Protege Client has to be restarted for it to work . Attached are the detailed Screen prints with logs 

[Issue 440.docx](https://github.com/NCIEVS/nci-protege5/files/4955832/Issue.440.docx)

**Comment by bdionne** [comment]
@singhik Would it be possible to see the logs?

**Comment by NCIEVS** [comment]
Hi @singhik , just to verify, this is with the 3.4.0-dev2 client, yes?  Did you try the use case 1 (manual edits only) already?

**Comment by NCIEVS** [comment]
@bdionne , the log is included in the word file.

**Comment by singhik** [comment]
@NCIEVS : Hello, yes Client is 3.4.0-dev 2 , Use Case 1 of Manual Edits is working fine with no lock or Save button issue noticed thus far , this Use Case of Batch Edits was not from Editors but was one of our Scenarios .

**Comment by bdionne** [comment]
@NCIEVS sorry I can't view that with pages, it probably kills it when it loads the docx format

Could we upload the log file to the GH ticket? Compressed if it's too large

**Comment by singhik** [comment]
@bdionne : Hi, Pfa Logs.txt  as a separate file .
[ProtegeLogs.txt](https://github.com/NCIEVS/nci-protege5/files/4955912/ProtegeLogs.txt)

**Comment by bdionne** [comment]
@singhik so just to double check, both instances were running on the same machine, so this log is for both of them?

And it's the instance running the batch load that hangs, at the end when it's committing? 

I suspect this is a different issue from the usually locking the editors are seeing, and is a problem in batch processing

**Comment by singhik** [comment]
@bdionne : Hi , 

1. This log is from the INstance which hangs when doing Batch Load .
2. Yes, both instances are running on the same machine. 
3. Batch Processing is working fine for stand-alone instances, it also works fine for multiple instances, when i close the instance which hung ,re-start it , and do the same Batch Edit (while the other instance is still locked on the same branch,same concept and same Project).

**Comment by bdionne** [comment]
> and do the same Batch Edit (while the other instance is still locked on the same branch,same concept and same Project).

@singhik by "locked" you mean the other instance is focused on that same branch, looking at the same concepts?

So to paraphrase, you're saying that the batch process doesn't always hang, just sometimes. When you restarted the app and ran the same batch again it worked. Is that correct?

I'm wondering if this scenario is a situation where the autoupdater, in the instance running the batch edit, is conflicting with the batch since it's long running and applies all the changes at once when it commits. Maybe what we should do is disable the autoupdater internally when we run a batch process and then enable it again after it completes.

**Comment by hahndane** [comment]
Hi Bob,


You said, “Maybe what we should do is disable the autoupdater internally when we run a batch process and then enable it again after it completes.”
Would this be automatic or would the editor need to disable/enable the autoupdater manually?

Thanks,
Liz

**Comment by singhik** [comment]
@bdionne : Hi,   Yes, with 'locked' i meant, the other instance is focused on the same branch,same concept of the same project .
                    It hangs for every first time and post re-start it works fine  .  

I disabled the 'Auto-UPdate' Manually in both instances and the issue is 'reproducible' and hangs at 'Committing Changes to the server' .

'Auto-Update' if by default is disabled then the Editors won't be able to see each other's changes at real time unless they Enable 'Auto-Update', but either ways, issue is reproducible with that being disabled as well .

**Comment by bdionne** [comment]
@singhik Thanks, this is very helpful. I think I may know what this is

**Comment by bdionne** [comment]
@singhik pretty sure this is a separate issue from the other freezes folks are reporting. I can reproduce this, with just a single instance, almost every time. All that's required is to use a small test case like the one you have in the document. I used 3 insertions for the batch load and it freezes every time.

We've also seen this in the old classifier and I'm pretty sure it relates to the JProgress bar not having enough time to update itself when the process completes too quickly. I'll play with it and see if I can sort this out. 

But I'm pretty sure this is a separate issue from all the freezes Liz et. al. see when multiple editors are working. Hopefully this new build is preventing those.

> Maybe what we should do is disable the autoupdater internally when we run a batch process and then enable it again after it completes.

> Would this be automatic or would the editor need to disable/enable the autoupdater manually?

@hahndane what I meant by "internally" is that we would do it programmatically. The user would not need to  disable/enable the autoupdater manually

I don't think we'll need this though, as this freeze has nothing to do with multiple instances.

**Comment by NCIEVS** [comment]
Ah yes, the fast classification wedge (#428), the classification would finish before the progress bar & finish dialog were called.  [That one had a workaround, but very likely because of the nature of the popup, modal vs modeless.]  I don't recall the fix, but I think it involved simply switching the order when the progress bar was called.

**Comment by bdionne** [comment]
ok, the batch edit freezes when using small datasets is fixed. Will be in the next EditTab push

**Comment by singhik** [comment]
@bdionne : Hi Bob,  Batch Load/Edit hung on 'Commiting Changes To Server' on multiple instances(two) of Protege Client and performing Batch Load on both on the same Concept . Attached are the screen prints and logs ::

Instance 2 : 

![image](https://user-images.githubusercontent.com/36314371/88849369-c1de1980-d1b7-11ea-8b4f-0a7c6dd21f9a.png)

Instance 1 : 

![image](https://user-images.githubusercontent.com/36314371/88849454-e934e680-d1b7-11ea-8a55-43b7330787d3.png)

Logs :: 

[logs.txt](https://github.com/NCIEVS/nci-protege5/files/4997298/logs.txt)

**Comment by bdionne** [comment]
Yes I saw something similar today when testing the export issues. I'm pretty sure thie [commit](https://github.com/NCIEVS/nci-edit-tab/commit/1dc01fc808fd659a65f7dfdc752daad1bb2504e8) will fix it, and it will be in the next `EditTab` push

**Comment by bdionne** [comment]
@singhik - I just pushed another change to `EditTab`, `1.1.6`, that will tighten this up further. I think having two modelers running batch loads simultaneously is likely a seldom used case.

Were they both running the exact same input file, .ie. trying to add the same classes? What you should see now will depend on the use case. If the autoupdater triggers in one client before it completes the batch load you may get an exception stating you have to update your client. This is because the other client commited first. You may see duplicate classes, but they really won't be dups, they will have different codes.

Are both instances running from the same app in the filesystem? Is this log the log they share or is there another one?

In any event give 1.1.6 a spin once you get the new build.

**Comment by singhik** [comment]
@bdionne : Hi, 

Input files are different for both instances , trying same input files on multiple instances is not a practical use case per my understanding hence is not used .
Both instances are running from two separate installation directories , the only thing they share is 'Project' (Which is fetched from server) and Platform (OS, RAM etc).
The log file i sent is from the instance which hung, yes there is another for the different instance , attaching that for your reference .

[protege.log](https://github.com/NCIEVS/nci-protege5/files/5002115/protege.log)

**Comment by bdionne** [comment]
> Input files are different for both instances , trying same input files on multiple instances is not a practical use case per my understanding hence is not used .

Agreed, actually running multiple batch edits is also unlikely. Could you attach the input files you used? I'd like to try the specific example with the latest plugin locally to see if it still hangs.

**Comment by singhik** [comment]
@bdionne : Hi, Attached are the two log files . 
[Load2.txt](https://github.com/NCIEVS/nci-protege5/files/5002264/Load2.txt)
[Load1.txt](https://github.com/NCIEVS/nci-protege5/files/5002265/Load1.txt)

**Comment by bdionne** [comment]
Thanks @singhik, so these two inputs both add children to the same parent and are very small. I tested it a few times and I didn't get any freezing. What I did get almost always is that one of them fails to commit changes because the local copy is out of date. One client commits first and the other needs to update. Sometimes you don't get it if the autoupdate has updated in between, but I only see that with the polling interval set to 5 seconds.

**Comment by NCIEVS** [comment]
Wasn't sure, but it did seem that those two files where hitting the same concepts.  @singhik , @bdionne, what would happens if the batch loads point to different parent concept?  I had thought that there would be no issues then, but if the isssue involves the local copy of one of them going stale the outcome might still be the same?

**Comment by bdionne** [comment]
> what would happens if the batch loads point to different parent concept?

I've tried that scenario also, and it doesn't cause a freeze. The only fail I see currently is that if you start them both as fast as you can one commits first and the other fails with a message to update the local copy. It's the sme message you get if two clients both save at the same time. Nick sees this a bit.

**Comment by singhik** [comment]
@bdionne @NCIEVS : Hi,  I am able to reproduce the hanging of Protege Instance  on 'Commiting Changes to Server' for 'Batch Edits' on multiple instances(two) on Same Parent Concepts only. When instances have different parents, the Hang on Commiting changes  does not occur. Below are the detailed Screen prints for the entire scenario .  

**Same Concepts ::** 

Instance 1
![image](https://user-images.githubusercontent.com/36314371/88958598-b8fc4f00-d26e-11ea-9696-81962d911b54.png)

Instance 2 (Hangs on Commiting changes to server)
 
![image](https://user-images.githubusercontent.com/36314371/88958687-d6311d80-d26e-11ea-9507-bbf435f26fd8.png)

**Different Concepts ::****

Instance 1 

![image](https://user-images.githubusercontent.com/36314371/88959250-b0f0df00-d26f-11ea-9732-d9464efbb653.png)


Instance 2 

![image](https://user-images.githubusercontent.com/36314371/88959266-b77f5680-d26f-11ea-8c54-7321c545711d.png)

Instance 1 

![image](https://user-images.githubusercontent.com/36314371/88959394-ee556c80-d26f-11ea-861d-10fac98cfe12.png)

Instance 2 

![image](https://user-images.githubusercontent.com/36314371/88959595-3d9b9d00-d270-11ea-9be1-c601c2ce992c.png)

Instance 1 

![image](https://user-images.githubusercontent.com/36314371/88959712-6e7bd200-d270-11ea-8dcc-8693bbba3892.png)


**NOW CHANGING THE INSTANCE 2 BATCH LOAD TO THE SAME CONCEPT AS INSTANCE 1** 

Instance 1 : 

![image](https://user-images.githubusercontent.com/36314371/88959839-a1be6100-d270-11ea-86c6-d57eb29ed552.png)

Instance 2 :  **(On same concept as Instance 1 )  and Instance 2 Hangs on Commiting Changes To Server** 

![image](https://user-images.githubusercontent.com/36314371/88960027-e4803900-d270-11ea-8acf-e2955e8f256c.png)

**Comment by bdionne** [comment]
@singhik is this with the latest build, `3.4.0-qa2`, and `EditTab` `1.1.6`?

**Comment by singhik** [comment]
@bdionne : no , this is 3.4.0-qa 1 and 1.1.6, i didn't know if the new build is released, will need to figure out its build process and client extraction ,if it's ready .

**Comment by bdionne** [comment]
ok, yea even `1.1.5` won't work well without the `3.4.0-qa2` build

**Comment by singhik** [comment]
@bdionne : Is the 'Help->About->Version' , updated in the build to highlight the latest and updated client version ?

**Comment by bdionne** [comment]
[yes](https://github.com/NCIEVS/protege/commit/d7327713b4705fcf2e53eded2f0cf0802cbf2607)

**Comment by bdionne** [comment]
That looks like the last production build @singhik 

Jenkins gets the tags from the `nci-protege5` repo. You can see the tags [here](https://github.com/NCIEVS/nci-protege5/tags) and the newest one is `3.4.0-qa2`

I"m not sure what command runs from Jenkins but what I do locally is run:
````
./build.sh 3.4.0-qa2 ncievs
````
If you look at the `3.4.0-qa2` tag of protege, [3.4.0-qa2](https://github.com/NCIEVS/protege/commits/3.4.0-qa2) you can see the last [commit](https://github.com/NCIEVS/protege/commit/d7327713b4705fcf2e53eded2f0cf0802cbf2607) was to update the version. That tells me it's there and when I build this locally it's what I see.

Perhaps you selected the wrong job to run in Jenkins? We can do a webex and screen share tomorrow if you're still stuck. I haven't used Jenkins in a while but I'm sure we can sort it out

**Comment by singhik** [comment]
@bdionne : Hi, Jenkins Job selected is correct, cause the same Job was used by @safrant  for 3.4.0-qa1 build . I also saw the 'version' as 3.3.0-qa1  for the build Tracy did for  Tag 3.4.0-qa1 . Jenkins Job console output is also attached

Job i ran today for 3.4.0-qa2 : 

![image](https://user-images.githubusercontent.com/36314371/88981055-1bffdd00-d293-11ea-8afc-d20fa1ebf1e6.png)

Job Tracy ran for 3.4.0-qa1 : 

![image](https://user-images.githubusercontent.com/36314371/88981079-27530880-d293-11ea-8ad4-8eea25196b97.png)


[Jenkins_Job_Console_Output.txt](https://github.com/NCIEVS/nci-protege5/files/5004092/Jenkins_Job_Console_Output.txt)

**Comment by bdionne** [comment]
@singhik - perhaps you're supposed to send arguments to the scripts? You have `3.3.1-qa1` showing up in the about panel, which is pretty old. 

I'm pretty sure that if Jenkins built the tag, `3.4.0-qa2` it will show in the about panel of protege. It did for me.

That console file you attached doesn't show the actual building. If you could get to that you can see the git checkout commands and see if it's doing something like
````
git checkout -b 3.4.0-qa2
````

**Comment by singhik** [comment]
@bdionne : Hi, arguments are supplied as part of the build Job, which shows in the screen print above as '85: 3.4.0-qa2' .  We select the Tag/Branch , which gets pulled from 'Git' , in this case that  is '3.4.0-qa2' . Also, the console output shows 'git checkout -f 7ab0d9b42d3461ed9cf4f4b5b6ccbf0b476c6924' ,  Attached screen print shows that : 

![image](https://user-images.githubusercontent.com/36314371/88984758-7a7d8900-d29c-11ea-8617-58a72acc8ce8.png)

![image](https://user-images.githubusercontent.com/36314371/88984853-caf4e680-d29c-11ea-9c20-939d3f25d29c.png)


![image](https://user-images.githubusercontent.com/36314371/88984997-3d65c680-d29d-11ea-92e4-3b36ab150c37.png)

![image](https://user-images.githubusercontent.com/36314371/88985288-d8f73700-d29d-11ea-9e0d-a200b0db78d5.png)

**Comment by singhik** [comment]
@bdionne : 3.4.0-qa2, does not look stable, has multiple issues, to quote a few : 

1. Warning prompt Pop-Ups for Disjoint and Redundant concept does not appear ::

![image](https://user-images.githubusercontent.com/36314371/89071406-a48a8600-d344-11ea-8631-44095030d5a8.png)

![image](https://user-images.githubusercontent.com/36314371/89071417-ac4a2a80-d344-11ea-9d68-746f90465407.png)

2. Amending or Adding a Parent to a Class, does not enable 'Save' button to Save the concept :: 

![image](https://user-images.githubusercontent.com/36314371/89071489-da2f6f00-d344-11ea-85e3-65124399de47.png)

![image](https://user-images.githubusercontent.com/36314371/89071497-e0255000-d344-11ea-94e2-b4aa2ba3296c.png)

3. Unable to 'Retire' and 'save' the Retired Concept as 'Save' button is not enabled to Save ::

![image](https://user-images.githubusercontent.com/36314371/89071616-1531a280-d345-11ea-8d2d-5af361c6b48a.png)

No Option to Save  the Retired COncept , only option works is to "Cancel' hence unable to Retire a concept

![image](https://user-images.githubusercontent.com/36314371/89071695-38f4e880-d345-11ea-8639-d0b0a44d45d8.png)

**Comment by bdionne** [comment]
@singhik Have you verified that this is a valid build of 3.4.0-qa2? That's not clear to me from all your earlier posts.

My impression is that you might be running the newest plugins on top of 3.3.1-qa1

**Comment by singhik** [comment]
@bdionne : I have verified the Jenkins Build pointing to the right tag(3.4.0-qa2), console output of the build and the QA server deployment , not sure what else to validate ,  so pretty positive for all the steps i followed being similar with @safrant  on deployment . If hypothetically i were to assume it being older build 3.3.1-qa1, then parent retree and save should work with that build too ?

**Comment by bdionne** [comment]
Hi @singhik,

We added the version feature to the about panel in Protege, per your request, so that you can validate that you have the correct build. Your own feature seems to indicate you do not.

You've verified that Jenkins pointed to the right tag but we haven't seen the log showing that indeed all the correct tags were checked out, and it looks like they are not. Do you think it's productive for me to continue to try and triage and reproduce `reported` errors whle you continue to use a possiby bad build? 

I did a build this morning, running the command:
````
./build.sh 3.4.0-qa2 ncievs
````
from a clean direcotry and so far everything you mentioned is not working works for me. My build also shows `3.4.0-qa2` in the about panel

>  I have verified the Jenkins Build pointing to the right tag(3.4.0-qa2), console output of the build and the QA server deployment , not sure what else to validate ,

Given that you cannot produce the right version, I think you need to see the git output form the build script execution, the logs you poset do not show any of that. If you'd like to post this new build somewhere I'm happy to look at it and compare the jar files to the good build I have.

> If hypothetically i were to assume it being older build 3.3.1-qa1, then parent retree and save should work with that build too ?

Actually not, if you've configured it to use the curator checks it will run those and throw an exception as there will be a missing method on the protege layer it calls

Let me know how I can help

**Comment by singhik** [comment]
@bdionne  :  Hi,  As far as the version display goes, yes that was a way for us to know that we have the right build  like a OS Display, but as i have said before the earlier builds for 3.4.0-qa1, 3.4.0-qa2 and 3.4.0-dev1  also reported the same incorrect version and @safrant  has noted them too .You have noted them too from your earlier emails .

No, i don;t want you to triage the defects if you think it's the build process and not the code, neither do i want to do infinite iterations of testing , so 

For now i will halt the testing completely and will triage with @safrant  on the built done for 3.4.0-qa2 , process followed , and if possible do a new one if there was an error done on my part while building .

**Comment by bdionne** [comment]
@singhik I think that's the prudent thing. Even the `3.4.0-qa1` build you showed me this morning also displays the incorrect version, and I thought @safrant did that build solely to get the new version nuber in there, as the `3.4.0-devx` builds were missing it. Anyway let's track this issue in #459

**Comment by singhik** [comment]
Below Use Cases are validated successfully on  build '3.4.0-qa2'  on NCI EDIT Plug-in 1.1.7 , hence closing the ticket .

Use Case 1 :: Two protégé client Instances , both instances on the same concept/Branch, performing Batch Load/Edit on one instance and doing other non-batch operations(f.e. Property Delete/Edit operations) on another instance .


Use Case 2 :: Two protégé client Instances , both instances on the same concept/Branch, performing Batch Load/Edit on one instance and doing other batch Load/Edit on another instance .

Use Case 3 :: Two protege client instances, one instance is locked on a Concept/Branch, other instance is performed with operations and re-tree of parents of the same Concept/Branch , the re-treeing of parents go down 3-4 level in hierarchy . After completion, the first instance should receive the edits done in the second instance and no freeze or hang should happen .
