### ISSUE TITLE
Unable To Create Concepts 

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#441]
@bdionne @NCIEVS : Hi, Have found a major issue with Concepts Creation on 3.3.0-qa2 build .Details are below ::

![image](https://user-images.githubusercontent.com/36314371/81109508-34589980-8ee8-11ea-95f4-e3fd90c478e3.png)

**Concept does not get created, Console to Save the Created Concept  **DOES NOT** appear ::**

![image](https://user-images.githubusercontent.com/36314371/81109630-5eaa5700-8ee8-11ea-9d7d-9eb46c3d1a70.png)

**Trying to Search the Concept, if in case it got created without  Save , unable to find ::**

![image](https://user-images.githubusercontent.com/36314371/81109866-c791cf00-8ee8-11ea-9c00-c7c5f76ed6a8.png)

**Plug-Ins Screen Shot for Reference ::**

![image](https://user-images.githubusercontent.com/36314371/81110183-33743780-8ee9-11ea-896f-0280797faa63.png)

**Comment by bdionne** [comment]
Good catch @singhik, though I'm not able to reproduce this. I have the same questions I posed on #442 with respect to detail.

One obvious issue to rule out is permissions. Does the user logged in have authority to create new concepts? This is likely not the problem because you would see a failure popup message with it fails to commit on the server, asking you to see the administrator

<img width="1019" alt="Screen Shot 2020-05-06 at 7 55 57 AM" src="https://user-images.githubusercontent.com/31741/81180486-1e46e980-8f79-11ea-9a70-2f2137e14d60.png">
<img width="1015" alt="Screen Shot 2020-05-06 at 8 21 20 AM" src="https://user-images.githubusercontent.com/31741/81180493-2010ad00-8f79-11ea-9960-3f145b04da49.png">

**Comment by singhik** [comment]
@bdionne : Hi, User logged in has 'WorkFlow Manager'  permissions , However , i am **able** to create concepts today with same user , not sure what changed ?

![image](https://user-images.githubusercontent.com/36314371/81185797-0888f280-8f80-11ea-98d4-6f95ab8e80b9.png)

![image](https://user-images.githubusercontent.com/36314371/81186606-fce9fb80-8f80-11ea-857a-c221c7f146a4.png)

**Comment by bdionne** [comment]
Happy to hear that @singhik mainly because I'm not able to see why this would start failing, there's nothing much changed in this area. @safrant can we get the current server log from late yesterday pushed somewhere? I'd like to see if there are any clues in there, maybe the server failed to commit but didn't tell the client, .eg. if it couldn't generate a code

**Comment by singhik** [comment]
@bdionne : Hi, So i Re-login with the same User, Concept Creation is **not** working now for the second concept , nothing changed .

![image](https://user-images.githubusercontent.com/36314371/81188267-1c822380-8f83-11ea-869f-7aeda4980a51.png)

Concept Not Created , No Save button on console is visible ::

![image](https://user-images.githubusercontent.com/36314371/81188360-3885c500-8f83-11ea-9b7e-fb35f20386d3.png)

**Comment by singhik** [comment]
@NCIEVS @bdionne : Thanks @NCIEVS , This is working fine after changing the Concept Code sequence Generator , have Executed numerous Regression via Automation , Hence closing the ticket .
