### ISSUE TITLE
modification of admin gui to include namespaces

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#444]
from @safrant in #371:
"I imported the 3 project above(20200205, ro.owl,ro-merged-clean.owl) into Protege on Dev using the Server Administration GUI. I notice that "namespace" is not an option in the "Edit Project" dialog. I need to manually add it to the JSON. Could we please have the namespace added? For extra special sauce, could the dialog display all namespaces available from the owl header so I can pick one?"

I've put it in for milestone 3.5.0 only because I couldn't find "future release"

**Comment by bdionne** [comment]
We should discuss this requirememt. Currently if you create a new project by importing an OWL file it derives the namespace from that file. If we allow the user to edit this will that create more confusion when the editor puts in something that doesn't agree?

I mention this based on the email thread from late today about prod/staging/etc.. and getting the config right

cc: @safrant @NCIEVS

**Comment by NCIEVS** [comment]
Yes, we can discuss it.  There might be some issues currently when creating a project using a template, can't say for sure yet.  But if the wrong namespace winds up there, the only way to change it is by deploying a new config or having a systems person change or edit it.

**Comment by bdionne** [comment]
I get that, I was questioning it because it seems this issue pertains more to migrating existing projects and I wasn't sure it was worth it for a one time usage.

pretty sure we tested this, but if there's a scenario where the software doesn't do the right thing, for sure we'll fix it.

My concern is that asking the user to put in a value then expecting it to agree with the file chosen will create other process issues. Also, as stated, displaying a pull down with all the namespace present in the header involves opening up the file first, which require more substantial change to the GUI as we'll have to know which file is being used first.

**Comment by NCIEVS** [comment]
I tested the namespace issue in DEV, and I didn't see it happening either with or without a template. 

Yeah, I don't think migrating an existing project will be the problem, the config file with the namespace (& imports) would be part of the deployment package.  We'd only use this enhanced functionality on a new project if a hiccup happens during the project creation.  Agreed on the dropdown.

**Comment by NCIEVS** [comment]
Will close this one.  Desirable only under very limited circumstances.
