### ISSUE TITLE
Protege exports invalid OWL after editor association error

### ISSUE THREAD

**Issue by safrant** [NCIEVS/nci-protege5#457]
An editor did a batch edit that resulted in multiple associations with invalid values.  Protege did not detect this.  During the next baseline export Protege created an invalid OWL file that could not be read by the OWLAPI.  There should be some way of detecting these errors either with a validity check or by outputting an error message during the RDF export. 

        <A24 rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#&quot;http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C168923"/>

**Comment by bdionne** [comment]
input files from modelers

[A23-24.txt](https://github.com/NCIEVS/nci-protege5/files/4988911/A23-24.txt)

console output
[A23-24O.txt](https://github.com/NCIEVS/nci-protege5/files/4988912/A23-24O.txt)

**Comment by bdionne** [comment]
@safrant This input file had problems but it doesn't produce the error as reported. It produces something like:

````
<owl:Class rdf:about="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C999999">
        <rdfs:subClassOf rdf:resource="http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Activity"/>
        <Concept_In_Subset>&quot;http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Gene</Concept_In_Subset>
        <Concept_In_Subset>http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Gene</Concept_In_Subset>
        <FULL_SYN>bad1</FULL_SYN>
        <Preferred_Name>bad1</Preferred_Name>
        <Semantic_Type>Activity</Semantic_Type>
        <code>C999999</code>
        <rdfs:label>bad1</rdfs:label>
    </owl:Class>
````

**Comment by bdionne** [comment]
This is reproducible, using the input file from the modelers. The issue is a bad input file. The records are quoting the URLs and adding a newline that forces the end quote into a separate record.

The dudplicate namespace in the value is because when we get a plain string as the property value for a property which has a type of `xsd:anyURI` we try to make an `IRI` out of it. If we can't then we prefix the striong with the namespace from the `CODE` property, as a default. These strings are not valid urls.

Next TODO is to discuss with the modelers and possibly enhance editing to strip quotes off some property values
