### ISSUE TITLE
3.5.0 Feedback from modelers on UAT

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#489]
Summary:

1. Protégé is behaving bizarrely.
2. Normal functionality isn’t working.
3. Definitions edited were not updated with date and name. (#396)
4. Concepts wouldn’t merge.
5. PT does not show up in the hierarchy.
6. In the middle of editing pop-ups like “Class already being edited; do you want to proceed” kept popping up and interfering with editing.
7. One editor would create a concept and that concept would appear on a different editors instance of protégé; that editor would have to save the concept; not the editor that created it. 
8. Lost Save button while reparenting

[@ncievs edit: changed bullets to numbers to tie to the issue report source in emails, see next comment.]

**Comment by NCIEVS** [comment]
Tie the above to the issue reports so that the logs can be found in the submitted emails, reporter & dateTime of report (in subject line)
1. Perceptions collected by LW, 10/28/2020 1:33 PM
2. as above, 10/28/2020 1:33 PM
3. EHD 10/28/2020 13:21:19, and CM via LW 10/28/2020 2:12 PM (email, no bug report)
6. AG 10/28/2020 13:23:11, and CM via LW 10/28/2020 1:49 PM (email, no bug report)
7. AG 10/28/2020 13:23:11 (in same report as above), GC 10/28/2020 13:28:51, GC 10/28/2020 13:48:24, and per LW "This happened to at least 4 editors" 10/28/2020 2:09 PM
8. NT 10/28/2020 13:21:30
9. EHD 10/28/2020 13:23:49 (while on standby), and EHD 10/28/2020 13:32:20 (after failure to manually update, eventually it worked with 362 changes)

One last report from NS via email, concerning frequency of manual updates, 10/28/2020 2:29 PM

**Comment by bdionne** [comment]
Most of these should be addressed in the latest 3.5.3 build

**Comment by bdionne** [comment]
modelers report most issues resolved in last UAT
