### ISSUE TITLE
Support / for IRI fragment

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#490]
This probably works already, just needs to be tested.  The switch to / to delimit the IRI "fragment" (legacy nomenclature) from the # is to make it easier to do things like redirection and concept reports from web servers.

**Comment by NCIEVS** [comment]
As I understand it, it turns out this doesn't work very well at the moment because the namespace returned when using # is not the same as when using / and the fragment that you get back is empty.  So this behavior would need to be fixed to make things consistent between # and /.

**Comment by bdionne** [comment]
correct, The `IRI` object in the OWLAPI returns an empty string when the `IRI` ends with a "/". The `getShortForm` method does the right thing, it looks if the remainer is empty and strips of the fragment from the full `IRI`. 

The panel for the refactor-rename action has similar issues, though it uses both the `IRI` and a `java.net.URL`

**Comment by NCIEVS** [comment]
Currently, if the separator is /, the class shows up as uneditable in the Description and General subtabs of nci-edit tab.

**Comment by bdionne** [comment]
Protégé makes the assumption that the fragment of the `IRI` begins from the last `/`, and `NCI` uses `#` in its `IRI`s in Thesaurus.

What complicates this is that in the Thesaurus owl file the top namespace declaration doesn't agree with the namespace specified in the about attribute of the ontology declaration.

`EditTab` compensated for all this by adding the `#` to the string returned from the call to retrieve the namespace of the ontology, so that it matches the `IRI` of the class.

It's not entirely clear what the spec says about namespaces, but it would seem a good solution, given how protégé works would be to fix the owl file and remove the check for the `#` in `EditTab`, unless the protégé exporter produce the owl file this way. In the latter we should fix protégé

**Comment by singhik** [comment]
@bdionne @Fragosog : Hi, Have performed Concept Creation ,Addition of Complex Pty,Addition of Simple Pty,Edition & Deletion of Properties, Search of Concepts, Validating IRI on Entities Tab to show / instead of # for created concepts. 
Please advice if  there are  other validations that need to be performed on the Thesaurus for this ticket ?

**Comment by singhik** [comment]
This is verified in 4.2.0-dev2 build and hence closed
