### ISSUE TITLE
Classification Fails With An Error On 3.6.0-dev6 Build

### ISSUE THREAD

**Issue by singhik** [NCIEVS/nci-protege5#506]
@bdionne @NCIEVS  : 

**Steps to Reproduce  :** 

Login to Protege Client 3.6.0-dev6 and open any workable project  (f.e. Thesaurus-3.6-21.03e  on QA Server) .
Perform few edits and run classification .

**Issue :** 

Classification throws an error in the form of a dialog prompt per below screen prints

![image](https://user-images.githubusercontent.com/36314371/116008414-66c04280-a5e2-11eb-9dbb-210b2db0bfc3.png)

![image](https://user-images.githubusercontent.com/36314371/116008419-6f187d80-a5e2-11eb-9cfd-464efc9bb7c4.png)

[logs.txt](https://github.com/NCIEVS/nci-protege5/files/6372920/logs.txt)

**Comment by bdionne** [comment]
wow, this for sure makes we wonder about the build, see #508, this is a missing jar file?

**Comment by singhik** [comment]
Looping @safrant  to comment

**Comment by bdionne** [comment]
@singhik @safrant 

I found the issue here, it's a build problem. The nci-curator plugin embeds an internal jar file, `jgrapht-jdk1.5-0.7.3.jar`, that gets extracted and put into the lib folder when the nci-curator plugin is installed through the autoupdater. 

I not sure how the client is built, if the updater is used or the plugins are merely copied, but the version of the embedded jar is older, and missing a class. I'm not sure why that is, since the version number is the same, but it's different. If you delete `jgrapht-jdk1.5-0.7.3.jar` from your lib folder and the nci-curator-0.0.8 four the plugins, and then reinstall it using the updater, it will work.

**Comment by singhik** [comment]
@bdionne  : Hi, yes, the workaround works manually, Thanks . Though the build process needs to be fixed to correct this step @safrant

**Comment by bdionne** [comment]
Build process seems to have resulted in a corrupted jar file.

**Comment by singhik** [comment]
Verified on 3.6.0-Dev7 Build and hence closed
