### ISSUE TITLE
popup menus in navigation pane fail to select correct class

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#511]
right click popups on classes in the nav tree are funky. the class needs to be first selected for the popup to populate correctly

This is broken out from #359

**Comment by singhik** [comment]
@NCIEVS  : Hi, you have mentioned in #359 about Concept navigation tree being applied to 'Revision History ' and 'Inference ' Tabs as well. But these two tabs do not have any right click options applicable to them hence these two will become Not Applicable for this enhancement option, please let know if otherwise ?

**Comment by NCIEVS** [comment]
Hi @singhik , yes, for the trees that don't normally have right-button popups, the correct behavior after the fix would be that they still don't have a popup menu (or they have their own and hasn't changed its behavior).  This fix afaik only applies to the tree in the main edit tab.
