### ISSUE TITLE
sync user preferences in Usages panel

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#515]
EditTab and Curator now both reuse the UsagePanel from protege in order to control which references are filtered out during retirements and/or curator edit checks.

This causes a conflict with the filters the use may choose when viewing the Usages pane in the Entities tab.
This can be kept in sync by adding a method that captures an inFocus event

**Comment by singhik** [comment]
@bdionne @NCIEVS   : Hi, not sure how to derive this ticket Functionally, a retire operation of a concept with usages and then a curator check, does not provide any scenario of a conflict in Entities tab as such ? 

This ticket can be tested and closed by calling the  newly added 'infocus.Java' listener at Code level and passing the usage exceptions as parameters to it and then validate the Exception handler being invoked correctly , all via Unit Test . 

Please share your thoughts if otherwise ?
