### ISSUE TITLE
Feedback from modelers on revision diff tab

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#71]
Each of these might result in one of more additional tickets:

 - in revision history, put in a "subtype" column next to "type".  Type only shows the OWL type, e.g Annotation property, but the editors are interested in "DEFINITION", "FULL_SYN", so on.

 - would be nice to display the rdfs:label of the concept in the "commits" widget in the lower left widget.

 - in the "authors" widget, it would be good to show the number of concepts (or include this number as well as the number of commits) as well as the number of conflicting concepts next to each author's name.

 - granularity of the "comment" in the "changes" widget, e.g. "add full_syn", "edit full_syn", rather than a plain "modify"

 - configure the columns in the "changes" widget (hide/unhide), the main columns of interest are the author, the change subject, and the comment if it's made more granular.  the actual changes in the "change details" widget could appear as one of the columns in "changes"

 - when there's a conflict in the "change details", it's missing the name of the editor associated with each conflicting change

 - line wrapping in "change details", otherwise long text in e.g. definitions gets lost

 - annotations on annotations don't show up in the revision history, only the parent annotation shows up as changed but without a visible change (as it's on its annotation):  e.g. change a full_syn term type from PT to SY, this change only shows as "full_syn"

**Comment by NCIEVS** [comment]
What is the Clear button for? When you hover over it there is a note saying "Reset selected change(s) to review-pending status" but I don't see a "pending status" anywhere. In the same vein, what is the Download button for the NCI Thesaurus ontology or the changes ontology?

I would note that currently we don't "see" property changes in prompt but these changes are found in the Revision History tab. Not sure if this is a good addition or just a neutral item.

I am not sure that reviewing (accept or reject) a change should appear as a new Changes entry with a conflict. On the other hand, I am not sure that the reject process that Gilberto tried to perform during the call worked out because it doesn't say whether he rejected one or more edits or if he accepted all of them. So if the review is going to be included then the action should be captured (possibly in the Review column, which is currently empty).

I am still confused about the workflow (maybe because the coding to run the entire process has not yet been completed). I think I mentioned this during the call but I don't see a way to accept all the changes, save to history and clear the Revision History tab.

The Change Details for the creation of a new or edit of an existing Complex Property should include the changes to the annotations. (This is similar to the last point in the list in Gilberto's message below.)

Questions for Nicole (because I am indifferent on some of the current functionalities in the Prompt tab):
1. Do we need to have more edits labeled as conflicts? In prod when we run Prompt, the list shows us which concepts have been touched by more than one editor as a conflict but the Revision History only labels the editing of specific annotations by multiple editors as conflicts. Do we need to have conflicts based on concepts rather than annotations? A scenario that came to me was if two editors added a DEF to one concept (maybe one or both was the result of a batch edit?) would we want that labeled as a conflict. (This may be a bad example because concepts with 2 NCI DEF are flagged as part of the pre-production process for publication.)  

2. Do we need to be able to navigate to the concepts as we review them? We can do this in the current Prompt tab but I am not sure if it is necessary to maintain that functionality. I don't use this feature often. Prompt also has a function where you can review the details for the baseline and edited forms of a concept side-by-side. This is another feature that I don't often use (mostly because the window that opens to allow the side by side comparison of the two forms is not well designed), but is this useful to you?

3. Do you think having a panel with a hierarchy view, so one can visualize the tree where the concept being reviewed is located, would be useful?

**Comment by NCIEVS** [comment]
When you Reject a change you become the owner of the edit and the original edit exists producing a conflict. All of these end up in the history and neither edit should appear in the evs_history.

Also the Server>Show change history window has another column in the Change Details that says Add Axiom or Remove Axiom (see screenshot below). This would be useful information to include in either the Changes or Change Details section in the Revision History tab.

**Comment by NCIEVS** [comment]
currently, 
- the workflow manager can see the number of concepts edited at the top left (the blank panels will have data if the user focuses on an edited concept)
- in Users tab the workflow manager can see the # of concepts edited/user and the number of conflicts.  There are also panels that show which concepts were edited by the selected editor and which concepts that editor touched that may have conflicting edits
-  clicking on an existing concept that has been edited and may have a conflict, you can see which edits were made and which editor did what (although this second option is more difficult to analyze because you have to select a change and then go into the subchanges to see what atoms were edited).

**Comment by bdionne** [comment]
Meet with Liz, NIcole, and see how these look with current usage. Line wrapping and qualifiers on annotations might be useful.

**Comment by bdionne** [comment]
see #505 #504 #503

After meeting with modelers we identified three enhancements to revision tab

**Comment by NCIEVS** [comment]
Just to enter the feedback from [EHD] and [NT], leading to 505, 504 and 503 above.

The only ones I care about are:
- in revision history, put in a 'subtype' column next to 'type'.  
- Type only shows the OWL type, e.g Annotation property, but the editors are interested in 'DEFINITION', 'FULL_SYN', so on.
- annotations on annotations don't show up in the revision history, only the parent annotation shows up as changed but without a visible change (as it's on its annotation):  e.g. change a full_syn term type from PT to SY, this change only shows as 'full_syn'
  - NT: granularity of the 'comment' in the 'changes' widget" could be nice, but def low priority
- And one I don't see here, which was a separate ticket that I don't know how to look up. please add a horizontal window slider to the Commits panel.
