### ISSUE TITLE
strike through concept names appear inappropriately

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#80]
When a concept is retired the name appears with a strikethrough. Than same name could be part of another concept name elsewhere and should not have the strikethrough

**Comment by NCIEVS** [comment]
reported [previously](https://github.com/protegeproject/protege/issues/10)

**Comment by NCIEVS** [comment]
This seems to have been fixed as a by-product of fixing related items.  Will label fixed & close it.

**Comment by fragosog** [comment]
Reopened.  It turned out that the strikethrough was inconsistent.  Sometimes the active class (that has a label similar to a retired class' label) is displayed with strikethrough, and sometimes it isn't.  Noticed this inconsistency in the search results widget of the role editing widget.  But it appears that the lucene search tab is more consistent showing the label with strikethrough.

**Comment by bdionne** [comment]
fixed in [4.3.0-dev1](https://github.com/NCIEVS/protege/tree/4.3.0-dev1)

**Comment by singhik** [comment]
Tested on 4.3.0-qa1 Build
